### ISSUE TITLE
Да се измисли начин за важни забележки

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#1]
Търсим начин да слагаме важни забележки, примерно нещо такова:
![image](https://cloud.githubusercontent.com/assets/1689586/23519099/6546c1a4-ff7e-11e6-9406-ae5b1095fd7e.png)

**Comment by mchaov** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by mchaov** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by mchaov** [comment]
Може да ползваме **NOTE или таблица с 2 клетки, като в едната ще сложим иконка

**Comment by tonyozhelev** [comment]
Може да го направим със speech bubble, който е отбелязан по-някакъв начин Някой от балончетата ще са си в стандартния формат и това, на което трябва да се обърне повече внимание, ще има примерно подобен тип удивителна в него. Идеята ми е да не се получава че към едно парче код да има някакви инструкции, и после под тях още някакви други и в текста още нещо описано, а всички инструкции, които са за кода да са си в балончетата.

**Comment by ndimov1990** [comment]
Вляво човечето от СофтУни хванало в ръката си "!", отдясно самата забележка.

**Comment by nakov** [comment]
Измислено е как да се вкарват **_важни забележки_**. Добавена е [нова секция в ръководството на писателите](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/wiki/%D0%9D%D0%B0%D1%81%D0%BE%D0%BA%D0%B8-%D0%BA%D1%8A%D0%BC-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D1%82%D0%B5#%D0%92%D0%B0%D0%B6%D0%BD%D0%B8-%D0%B7%D0%B0%D0%B1%D0%B5%D0%BB%D0%B5%D0%B6%D0%BA%D0%B8).
