### ISSUE TITLE
Wiki: речник на термините

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#10]
Wiki: речник на термините. наков да го направи и другите ще допълнят.

**Comment by vncpetrov** [comment]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/wiki/%D0%A0%D0%B5%D1%87%D0%BD%D0%B8%D0%BA-%D0%BD%D0%B0-%D1%82%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%B8
