### ISSUE TITLE
Липсва точка

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#100]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
Липсва точка
## Текущ текст
Това, което знаем от условието на задачата, е че диамантът е с размер n x n
## Текст след поправката
Това, което знаем от условието на задачата, е че диамантът е с размер n x n.

**Comment by udarensamolet** [comment]
Fixed with [7b5deee](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/7b5deee473604c2be1e08343e22c90bb9db1a683)
