### ISSUE TITLE
Счупена таблица

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#103]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
Таблицата която е над този текст е разделена на две.Първата част от нея трябва има специален знак който показва че е важно както другите таблици по нагоре в тази глава!! 
## Текущ текст
Ако сме написали всичко коректно, задачата ни е решена.

Тестване в Judge системата

Тествайте решението си тук: https://judge.softuni.bg/Contests/Practice/Index/512#9
## Текст след поправката
Трябвада се оправи таблицата

**Comment by udarensamolet** [comment]
Проблемът не може да бъде симулиран. През Chrome и Mozilla специалният знак се визуализира, в GitBook също, на телефон и на таблет също няма проблем. Може би проблемът е локален.

**Comment by Tuscann** [comment]
На Firefox -  Нормална по размер иконка като другите на страницата
На Microsoft Edge - Нормална по размер иконка като другите на страницата
На Chrome - Малка иконка в сравнение със другите на същата страница 
На Орега - Малка иконка в сравнение със другите на същата страница 
На Yandex.Browser - Малка иконка в сравнение със другите на същата страница
