### ISSUE TITLE
Липсваща точка

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#104]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
Липсваща точка
## Текущ текст
Да се разработи ASP.NET MVC уеб приложение за визуализация на рейтинг (число от 0 до 100). Чертаят се от 1 до 10 звездички (с половинки). Звездичките да се генерират с for цикъл
## Текст след поправката
Да се разработи ASP.NET MVC уеб приложение за визуализация на рейтинг (число от 0 до 100). Чертаят се от 1 до 10 звездички (с половинки). Звездичките да се генерират с for цикъл.

**Comment by udarensamolet** [comment]
Fixed with [b4c8250](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/b4c825010658c2563b76f20e8b9a581e9bf54473)
