### ISSUE TITLE
Липсваща точка

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#105]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
Липсваща точка
## Текущ текст
Във Visual Studio създаваме ново ASP.NET MVC уеб приложение с език C#. Добавяме нов проект от [Solution Explorer] -> [Add] -> [New Project…] . Даваме смислено име, например "WebApp-Ratings"
## Текст след поправката
Във Visual Studio създаваме ново ASP.NET MVC уеб приложение с език C#. Добавяме нов проект от [Solution Explorer] -> [Add] -> [New Project…] . Даваме смислено име, например "WebApp-Ratings".

**Comment by udarensamolet** [comment]
Fixed with [b4c8250](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/b4c825010658c2563b76f20e8b9a581e9bf54473)
