### ISSUE TITLE
Грешка?

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#109]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-8-exam-preparation.md
## Описание
Защо S е със главна буква а другите с малка?
По важния въпрос **Страната на триъгълника S**
Трябва да е лицето на триъгълника.

## Текущ текст
Страната на триъгълника а = 6 - 1 = 5
Височината на триъгълника h = 1 - (-2) = 3
Страната на триъгълника S = a * h / 2 = 5 * 3 / 2 = 7.5
## Текст след поправката
Страната на триъгълника а = 6 - 1 = 5
Височината на триъгълника h = 1 - (-2) = 3
Лицето на триъгълника s = a * h / 2 = 5 * 3 / 2 = 7.5

**Comment by udarensamolet** [comment]
Стандартното означение за лице в математиката е с буквата 'S'.

**Comment by Tuscann** [comment]
Оправила си го че трябва да бъде лицето на триъгълника S а не както беше преди Страната на триъгълника S .
