### ISSUE TITLE
Грешка при изписване

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#115]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-8-exam-preparation.md
## Описание
пропусната буква с в пресмятания
## Текущ текст
няколко вложени проверки и прости премятания
## Текст след поправката
няколко вложени проверки и прости пресмятания

**Comment by udarensamolet** [comment]
Fixed with [23b0270](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/23b02703abf0a8becea2d7ef5ba2f3dcb8571070)
