### ISSUE TITLE
Грешка в примера снимката

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#116]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-8-exam-preparation.md
## Описание
Грешка в примера снимката

3 5 6 7
3 5 6 7

**Защо се повтаря два пъти?**
## Текущ текст
Изходът съдържа всички търсени четворки числа, в нарастващ ред, по една на ред.

Примерен вход и изход

Вход	Изход	Вход	Изход
3
7	3 4 5 6
3 4 5 7
3 4 6 7
3 5 6 7
3 5 6 7
4 5 6 7

**Comment by udarensamolet** [comment]
Fixed with [aed45b6](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/aed45b6724020bde99719395f078db8794224378)
