### ISSUE TITLE
Неяснота несъотвествие между картинките (да се оправят картинките)

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#118]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-10-tricks-and-hacks.md
## Описание
Ще сложим стопер (breakpoint) на функцията Console.WriteLine(...). За целта трябва да преместим курсора на реда, който печата на конзолата, и да натиснем [F9]. Появява се точка на прекъсване, където програмата ще спре изпълнението си:

**Breakpoint на снимката под този текст е на ред 15**

След стартиране на програмата виждаме, че тя спира изпълнението си на ред 11, където сложихме стопера (breakpoint). Кодът на текущия ред се оцветява с жълт цвят и можем да го изпълняваме постъпково. За да преминем на следващ ред използваме клавиш [F10]. Забелязваме, че кодът на текущия ред все още не е изпълнен. Изпълнява се, когато преминем на следващия ред:

**Breakpoint на снимката под този текст е на ред 11**

**Една е съща програма на двете картинки различен ред на breakpoint неяснота**
Казваш 11 ред пак като погледнеш първата картинка се оказва 15 ред???

**Comment by udarensamolet** [comment]
Fixed with [c79cef2](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/c79cef24e4ffbac16b452e4c34a2473d53abb767) and [d11deed](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/d11deed7c9389786228ae06c73f80af163d2fd04).
