### ISSUE TITLE
Грешка - запетая вместо знак

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#119]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-10-tricks-and-hacks.md
## Описание
Никъде не виждам запетая??
## Текущ текст
вторият е числото, което определя с колко знака след десетичната **запетая** ще закръглим (това число винаги трябва да бъде цяло число)
## Текст след поправката
вторият е числото, което определя с колко знака след десетичната знак ще закръглим (това число винаги трябва да бъде цяло число)

**Comment by udarensamolet** [comment]
Fixed with [f54cdfd](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/f54cdfd42b8b6c5a673c73549bf6c4e98e0a6af6)
