### ISSUE TITLE
Липсващ линк към Facebook група

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#121]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-0-preface.md
## Описание
Някои да направи Facebook група и да сложи линк.
## Текущ текст
Официална FB група на книгата

// TODO

**Comment by nakov** [comment]
Оправено.
