### ISSUE TITLE
Пропуснато bold подчертаване

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#122]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-4-complex-conditions-exam-problems.md
## Описание
От 5 до 9 – 60% от бюджета.    до не e bold 
## Текущ текст
Запалянковците имат определен бюджет, a броят на хората в групата определя какъв процент от бюджета трябва да се задели за транспорт:

От 1 **до** 4 – 75% от бюджета.
От 5 до 9 – 60% от бюджета.
От 10 **до** 24 – 50% от бюджета.
От 25 **до** 49 – 40% от бюджета.
50 или повече – 25% от бюджета.
## Текст след поправката
От 1 **до** 4 – 75% от бюджета.
От 5 **до** 9 – 60% от бюджета.
От 10 **до** 24 – 50% от бюджета.
От 25 **до** 49 – 40% от бюджета.
50 или повече – 25% от бюджета.

**Comment by udarensamolet** [comment]
Fixed with [b85182a](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/b85182a847d5a9899597135f7ba04cb44c5c7051).
