### ISSUE TITLE
 Излишни ** на две места

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#123]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-4-complex-conditions-exam-problems.md
## Описание
 излишни ** на **две места**
## Текущ текст
На първия ред е бюджетът – **реално число в интервала [1 000.00 ... 1 000 000.00].
На втория ред е категорията – "VIP" или "Normal".
На третия ред е броят на хората в групата – **цяло число в интервала [1 ... 200].
## Текст след поправката
На първия ред е бюджетът – реално число в интервала [1 000.00 ... 1 000 000.00].
На втория ред е категорията – "VIP" или "Normal".
На третия ред е броят на хората в групата – цяло число в интервала [1 ... 200].

**Comment by udarensamolet** [comment]
Fixed with [55e5dcb](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/55e5dcb6402cc64f2a3bdfef55a53cb762a0ca40).
