### ISSUE TITLE
Неяснота свързана с какво се принтира

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#125]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-4-complex-conditions-exam-problems.md
## Описание
На други места в книгата слагаме картинка какво се разпечатва на конзолата като изход тука няма.
## Текущ текст
Отпечатване на резултата

Накрая ни остава да покажем изчисления резултат на конзолата.

**Comment by Antoveravip** [comment]
Идеята ми беше на първите задачи да е показано как става извеждането на резултата на конзолата, а на по-крайните задачи го оставих нарочно да не е напълно показано решението на задачата. 

Но сложете снимка ако са променени инструкциите и навсякъде ще го показваме.

**Comment by udarensamolet** [comment]
Нарочно не е сложена картинка. 

@Antoveravip Точно такава е идеята при изпитните задачи.
