### ISSUE TITLE
Неяснота свързана със главната буква на месеци

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#126]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-4-complex-conditions-exam-problems.md
## Описание
Защо само първите месеци със главна буква?
## Текущ текст
Май и октомври	Юни и септември	Юли и август
## Текст след поправката
Май и Октомври	Юни и Септември	Юли и Август

**Comment by udarensamolet** [comment]
Защото са заглавия на колоните в таблицата.
