### ISSUE TITLE
Снимката да се оправи

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#127]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-4-complex-conditions-exam-problems.md
## Описание
Става въпрос за снимката която е под този текст.
В кода е излишно **:F2**
string apartmentInfo = string.Format("Apartment: {0:**:F2**} lv.", decimal.Round(apartmentRent, 2));

Защо трябва да слагаме **:F2** като преди това сме го загръглили до втори знак със decimal.Round(apartmentRent, 2));

## Текущ текст
След като изчислихме какви са съответните цени и крайната сума за престоя - нека да си изведем във форматиран вид резултата, като преди това го запишем в изходните ни параметри - studioInfo и apartmentInfo.

**Comment by Antoveravip** [comment]
Защо трябва да слагаме :F2 като преди това сме го загръглили до втори знак със decimal.Round(apartmentRent, 2));

Тествай първо ако ти е цяло число резултата и ще разбереш идеята от използването на :F2!!!
