### ISSUE TITLE
Картинката трябва да се отреже отгоре

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#128]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
Разстоянието над картиката е видимо по голямо от това под картинката.

## Текущ текст
Разбираме от условието на задачата, че къщата е с размер n x n. Това, което виждаме от примерните вход и изход, е че:

Къщичката е разделена на 2 части: покрив и основа.

**Comment by udarensamolet** [comment]
Fixed with [d44581f](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/d44581ff99bea577e46e36d27d28e235dad7307b)
