### ISSUE TITLE
blank solution написано със малки букви

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#129]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-5-loops.md
## Описание
Защо blank solution е със малка буква само тук.
## Текущ текст
Празно Visual Studio решение (Blank Solution)

Създаваме празно решение (Blank Solution) във Visual Studio, за да организираме по-добре задачите за упражнение. Целта на този **blank solution** e да съдържа по един проект за всяка задача от упражненията.
## Текст след поправката
Празно Visual Studio решение (Blank Solution)

Създаваме празно решение (Blank Solution) във Visual Studio, за да организираме по-добре задачите за упражнение. Целта на този *Blank Solution e да съдържа по един проект за всяка задача от упражненията.

**Comment by udarensamolet** [comment]
С големите букви копира начина на изписване във Visual Studio.
