### ISSUE TITLE
Да се промени снимката 

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#132]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-5-loops.md
## Описание
Имам предвид последната снимка отнасяща се за Задача: * Чертане на спирален триъгълник с костенурката
На предните фигури казваме да се добави бутон [името на бутона] и на снимката се вижда бутон със такова име.
На снимката няма бутон **[Triangle] а бутон [Draw].**
## Текущ текст
Задача: * Чертане на спирален триъгълник с костенурката

Добавете бутон **[Triangle]**, който чертае три триъгълника с по 22 върха като на фигурата по-долу:

**Comment by vncpetrov** [comment]
Fixed.
