### ISSUE TITLE
Грешката в таблицата

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#133]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
3 таблица примерен изход 2 ред последно число е на следващия ред ??
Може да събере на втория ред. 

## Текущ текст
Входни данни

Входът се чете от конзолата и се състои от две цели числа: n и l в интервала [1…9], по едно на ред.

Изходни данни

На конзолата трябва да се отпечатат всички “тъпи” пароли по азбучен ред, разделени с интервал.

Примерен вход и изход

Вход	Изход	Вход	Изход
2
4	11aa2 11ab2 11ac2 11ad2 11ba2 11bb2 11bc2 11bd2 11ca2 11cb2 11cc2 11cd2 11da2 11db2 11dc2 11dd2	3
1	11aa2 11aa3 12aa3 21aa3 22aa3
Вход	Изход	Вход	Изход
3
2	11aa2 11aa3 11ab2 11ab3 11ba2 11ba3 11bb2 11bb3 12aa3 12ab3 12ba3 12bb3 21aa3 21ab3 21ba3 21bb3 22aa3 22ab3 22ba3 22bb3

**Comment by Teodor92** [comment]
Форматирането става автоматично и това нямам как да се промени лесно.
