### ISSUE TITLE
Излишни звездички

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#134]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
Излишни звездички два броя
## Текущ текст
Прочитане на входните данни – в настоящата задача това включва прочитането на две числа **n**и l, всяко на отделен ред.
## Текст след поправката
Прочитане на входните данни – в настоящата задача това включва прочитането на две числа n и l, всяко на отделен ред.

**Comment by udarensamolet** [comment]
Fixed with [f447b63](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/f447b634fefa04ac669e4b58a9b6761fea1a0420).
