### ISSUE TITLE
Малки букви трябва да са големи

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#135]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
Малки букви трябва да са големи.
След : трябва да е следващия ред със Големи букви.
## Текущ текст
Знаете ли, че:

можем да дефинираме for цикъл с променлива от тип char:

и можем да прочетем променлива от тип char от конзолата със следната конструкция:

както и да обърнем главен символ към малък, използвайки вградена функция в C#:

## Текст след поправката
Знаете ли, че:

Можем да дефинираме for цикъл с променлива от тип char:

Можем да прочетем променлива от тип char от конзолата със следната конструкция:

Можем да обърнем главен символ към малък, използвайки вградена функция в C#:

**Comment by udarensamolet** [comment]
Fixed with [1b80582](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/1b805820a1f613cf4ce0e95a09acf8a17984268a).
