### ISSUE TITLE
Неяснота прочит

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#136]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
прочит - неясна дума прочитане 
## Текущ текст
Съответно, при **прочит** на символи от конзолата, директно можем да преобразуваме главни към малки букви, обединявайки горните два реда:
## Текст след поправката
Съответно, при прочитането на символи от конзолата, директно можем да преобразуваме главни към малки букви, обединявайки горните два реда:

**Comment by udarensamolet** [comment]
Прочит и прочитане са думи с еднакво значение

**Comment by Tuscann** [comment]
Добре според мен по правилната дума е прочитане в случая.
