### ISSUE TITLE
Излишно повторение на цял ред в условието

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#137]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
Повтаряне на един е същи ред два пъти.
## Текущ текст
Пример: "Магическо число" → 2

111112 → 1 * 1 * 1 * 1 * 1 * 2 = 2
111112 → 1 * 1 * 1 * 1 * 1 * 2 = 2
## Текст след поправката
Пример: "Магическо число" → 2

111112 → 1 * 1 * 1 * 1 * 1 * 2 = 2

**Comment by udarensamolet** [comment]
Fixed with [286b748](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/286b748e296e68ec9375fa1495029e8a5ba5e402).
