### ISSUE TITLE
Грешка в таблицата

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#138]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
Всяко **магическо число е нов ред** 
Условие: На конзолата трябва да се отпечатат всички магически числа, разделени с интервал.
Първия примерен изход изглежда грешен всяко на нов ред.
## Текущ текст
Входни данни

Входът се чете от конзолата и се състои от едно цяло число в интервала [1…600000].

Изходни данни

На конзолата трябва да се отпечатат всички магически числа, разделени с интервал.

Примерен вход и изход

Вход	Изход	
2	
**111112 
111121
111211 
112111 
121111 
211111**

**Comment by udarensamolet** [comment]
Форматирането става автоматично.

**Comment by Tuscann** [comment]
Това става **автоматично** нещо не ми звучи убедително.

**Comment by udarensamolet** [comment]
В такъв случай, моля за предложение за конструктивно решение, което да спомогне за отстраняване на проблема.

**Comment by Tuscann** [comment]
Трябва да се раздели на две отделни таблици а не както е във момента.
Ще има достатъчно место 

https://gyazo.com/af0fbd852ef7c00deab59d88a04e5e07
