### ISSUE TITLE
Грешен знак

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#139]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
Грешен знак ><  вместо ≤
## Текущ текст
M - цяло число: N **><** M ≤ 10000.
## Текст след поправката
M - цяло число: N ≤ M ≤ 10000.

**Comment by udarensamolet** [comment]
Fixed with [4a82efd](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/4a82efddd36dc1a21589ef974ba93755668bd476)
