### ISSUE TITLE
Глава работа с Console. Input/Output

### ISSUE THREAD

**Issue by ROSSFilipov** [SoftUni/Programming-Basics-Book-CSharp-BG#14]
Глава относно работа с Console/Input/Output в случай, че не е обособена такава.

**Comment by Teodor92** [comment]
Това май ще влезе към Чертане на фигурки с цикли

**Comment by nakov** [comment]
Материалът е вкаран в другите глави, по малко на различни места. Не е планирано да има такава глава, за да не се навлиза в големи подробности.
