### ISSUE TITLE
Излишна дума

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#140]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
точно - може и без тази дума не дава никакъв смисъл
## Текущ текст
От конзолата се четат **точно** 3 числа, всяко на отделен ред:
## Текст след поправката
От конзолата се четат 3 числа, всяко на отделен ред:

**Comment by udarensamolet** [comment]
Fixed with [1e63837](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/1e63837ad25a8b74ab9b899a28ab99d44f3f9250)
