### ISSUE TITLE
Грешка при показването на изхода в таблица

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#141]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
Таблицата след тозr текст:
По условие: На конзолата се принтират на **един ред,** разделени с интервал, всички числа, отговарящи на условията.
Вход	Изход	
1             **30 24** 
30           **18 12**  
15            **6**

**Как числата станаха на 3 реда??**
	

## Текущ текст
От конзолата се четат точно 3 числа, всяко на отделен ред:

N - цяло число: 0 ≤ N < M.
M - цяло число: N >< M ≤ 10000.
S - цяло число: N ≤ S ≤ M.
Изход

На конзолата се принтират на един ред, разделени с интервал, всички числа, отговарящи на условията.

Примерен вход и изход

**Comment by udarensamolet** [comment]
Автоматично форматиране, на различните устройства се визуализира по различен начин.
