### ISSUE TITLE
Грешно показване на таблица

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#142]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md
## Описание
Таблицата след този текст
(1 + 3) = 4 и (1 + 2) = 3 → **4 реда по 3 числа на всеки ред**

Аз виждам само един ред **129 126 123 120 119 121 123 120 119 121 123 120**

**Втория пример изход е сгрешен** по същия начин няма да го пиша като отделен проблем.

## Текущ текст
Входът се чете от конзолата и е цяло число в интервала [100...999].

Изходни данни

На конзолата трябва да се отпечатат всички цели числа, които са резултат от дадените по-горе изчисления в съответния брой редове и колони, както в примерите.

Примерен вход и изход

**Comment by udarensamolet** [comment]
Fixed with [bf0da98](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/bf0da98d678d3c8775164afd1ff7ae1f4d7d3e33).
