### ISSUE TITLE
Грешна буква

### ISSUE THREAD

**Issue by ivanov256** [SoftUni/Programming-Basics-Book-CSharp-BG#143]
## Линк към файла
https://csharp-book.softuni.bg/chapter-1-first-steps-in-programming.html
## Описание
...езици за програмира**м**е, вместо за програмира**н**е
## Текущ текст
Съществуват различни видове езици за програмираме. С една част от тях могат да бъдат написани самите инструкции, които управляват процесора, или инструкции, които управляват RAM паметта на компютъра. Пример за такъв език е "Assembler". С друга част могат да бъдат създадени операционна система, драйвер за видеокарта и т.н. Самият софтуер, който използваме ежедневно, като музикален плеър, видеоплеър, GPS програма и т.н., се пише на езици като C#, Java, Python, C, C++, HTML5 и др. +

## Текст след поправката
Съществуват различни видове езици за **програмиране**. С една част от тях могат да бъдат написани самите инструкции, които управляват процесора, или инструкции, които управляват RAM паметта на компютъра. Пример за такъв език е "Assembler". С друга част могат да бъдат създадени операционна система, драйвер за видеокарта и т.н. Самият софтуер, който използваме ежедневно, като музикален плеър, видеоплеър, GPS програма и т.н., се пише на езици като C#, Java, Python, C, C++, HTML5 и др. +

**Comment by udarensamolet** [comment]
Fixed
