### ISSUE TITLE
Излишен предлог

### ISSUE THREAD

**Issue by ivanov256** [SoftUni/Programming-Basics-Book-CSharp-BG#144]
## Линк към файла
https://csharp-book.softuni.bg/chapter-1-first-steps-in-programming.html
## Описание
Излишен предлог "на"
## Текущ текст
Поставяме целия код на програмата в черното поле и избираме C# code, както е **на** показано тук:
## Текст след поправката
Поставяме целия код на програмата в черното поле и избираме C# code, както е  показано тук:

**Comment by udarensamolet** [comment]
Fixed with [3621c9f](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/3621c9f4b4e278e977ecfceb2308c034d8ed5258)
