### ISSUE TITLE
Снимката да се оправи

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#145]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-1-first-steps-in-programming.md
## Описание
Става въпрос за снимката под този текст.
Горната програма може да тествате тук: https://judge.softuni.bg/Contests/Practice/Index/503#0 към judje
На снимката долу е https://judge.softuni.bg/Contests/Practice/Index/150#0

Несъотвествие между двата линка.**503#0                  150#0**

## Текущ текст
Поставяме целия код на програмата в черното поле и избираме C# code, както е на показано тук:

**Comment by udarensamolet** [comment]
Fixed
