### ISSUE TITLE
Снимката трябва да се промени и грешен линк

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#146]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-1-first-steps-in-programming.md
## Описание
Става въпрос за снимката под този текст.
Стартираме програмата с [Ctrl+F5] и проверяваме дали резултатът е същия:

Тестване в Judge системата

Тествайте решението си тук: https://judge.softuni.bg/Contests/Practice/Index/503#0
Горната програма може да тествате тук: https://judge.softuni.bg/Contests/Practice/Index/503#0 към judje
**Трябва да бъде https://judge.softuni.bg/Contests/Practice/Index/503#1 за да сочи към правилната задача.**

На снимката долу е https://judge.softuni.bg/Contests/Practice/Index/150#1

**Несъотвествие между двата линка.503#1 150#1**

**Comment by udarensamolet** [comment]
Fixed
