### ISSUE TITLE
Липсва bold на текст.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#147]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-1-first-steps-in-programming.md
## Описание
Защо textBoxSum не е bold като другите в този текст?
## Текущ текст
Този код взима първото число от полето textBox1 и го запазва в променливата num1, запазва второто число от полето textBox2 в променливата num2, след това сумира num1 и num2 в променливата sum и накрая извежда текстовата стойност на променливата sum в полето **textBoxSum**.

**Comment by vncpetrov** [comment]
Fixed. [bfb608ee964f6cb8e4a7c81000e2c7a882118191](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/bfb608ee964f6cb8e4a7c81000e2c7a882118191)
