### ISSUE TITLE
Излишни **

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#148]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-1-first-steps-in-programming.md
## Описание
Излишни ** пред /home/calculate

и една звезда след **контролера)*.**

## Текущ текст
Този код създава една уеб форма с три текстови полета и един бутон в нея. В полетата се зареждат стойности, които се изчисляват предварително в обекта ViewBag. Указано е, че при натискане на бутона [Calculate] ще се извика действието **/home/calculate (действие calculate от home контролера)*.
## Текст след поправката
Този код създава една уеб форма с три текстови полета и един бутон в нея. В полетата се зареждат стойности, които се изчисляват предварително в обекта ViewBag. Указано е, че при натискане на бутона [Calculate] ще се извика действието /home/calculate (действие calculate от home контролера).

**Comment by vncpetrov** [comment]
Fixed. [e8911d643baf06d26bc09231a553e76a4db38cca](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/e8911d643baf06d26bc09231a553e76a4db38cca)
