### ISSUE TITLE
Преименуване на главите за по добра навигация

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#149]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG
## Описание
Да преименуваме имената на главите така че да се показват правилно азбучно 
chapter-10 и chapter-11

chapter-00
chapter-01
chapter-02

## Текущ текст
chapter-1-first-steps-in-programming.md">chapter-1-first-steps-in-programming.md

## Текст след поправката
chapter-01-first-steps-in-programming.md">chapter-1-first-steps-in-programming.md
и другите глави по същия начен

**Comment by vncpetrov** [comment]
Done.
