### ISSUE TITLE
Глава "Хитрости и хакове"

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#15]
Глава "Хитрости и хакове" ще съдържа ей-такива неща:

- Именуване на проекти, файлове, променливи
- Shortcuts in VS, примерно [Ctrl+F] [Ctrl+F], Comment code, ...
- Code snippets - как да си направим Code Snippet: `cri` -> `int i = int.Parse(Console.ReadLine());`
- Дебъгване на код - работа с [F10], [F10] и breakpoints
- Форматиране на кода - препоръки
- Cheat sheet: така се прави цикъл, така се прави проверка, така се форматира с 2 десетични цифри.

**Comment by KaPrimov** [comment]
Не знам колко ще е полезно, но тaзи страница я използвах в Programming Basics и може да има нещо интересно: https://msdn.microsoft.com/en-us/library/dn320181.aspx

**Comment by jerih0n** [comment]
Благодаря! Има доста добре събрана информация на едно място и определено ще е от полза
