### ISSUE TITLE
Грешка при форматирането

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#150]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console-exam-problems.md
## Описание
Защо колони е bold а реда не е bold.Няма консистенция.
## Текущ текст
Да се напише програма, която прочита от конзолата цяло число n и чертае пеперуда с ширина 2 * n - 1 **колони** и височина 2 * (n - 2) + 1 реда като в примерите по-долу. Лявата и дясната ѝ част са широки n - 1.

**Comment by vncpetrov** [comment]
Fixed. [7e39f738007ffbb93af1d81a3279598f0bfcf96e](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/7e39f738007ffbb93af1d81a3279598f0bfcf96e)
