### ISSUE TITLE
Грешка при форматирането на текста

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#152]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops.md
## Описание
Защо първото ако е bold на следващия пример нем?
Защо от 1 до 2^n е bold a  на 2 до 2^n не е bold?

## Текущ текст
Да се напише програма, която отпечатва числата от **1 до 2^n** (две на степен n). Например, **ако** n = 10, то резултатът ще е 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024.

Тестване в Judge системата

Тествайте решението си тук: https://judge.softuni.bg/Contests/Practice/Index/514#2

Пример: Четни степени на 2

Да се отпечатат четните степени на 2 до 2^n: 2^0, 2^2, 2^4, 2^8, …, 2^n. Например, ако n = 10, то резултатът ще е 1, 4, 16, 64, 256, 1024

**Comment by vncpetrov** [comment]
Fixed. [42b69e8fdfbddd5333e5cc0001d8eed2d63a3460](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/42b69e8fdfbddd5333e5cc0001d8eed2d63a3460)
