### ISSUE TITLE
Лошо качество на снимки

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#156]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md
## Описание
Снимките които са между посочения текст са много некачествени вижда се.
По добре е да се направи като текст на нов ред. 
## Текущ текст
Изразът

бива решен по следния начин:

Бони е доста красива, но не чак толкова съобразителна, затова тя има нужда от нашата помощ, за да усвои силата на Изразите.

**Comment by Tuscann** [comment]
Защо трябва да е със снимки? 
С написан текст е много по добро качество после в учебника

**Comment by udarensamolet** [comment]
Проблемът най-вероятно е локален. Визуализацията е тествана на няколко устройства с няколко браузъра, проблема не можа да бъде симулиран.
