### ISSUE TITLE
Неяснота в текста

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#157]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md
## Описание
Входните **ни** данни
Не може ли без частицата ни?

## Текущ текст
Обработване на входа

Входните ни данни се състоят от точно един ред от конзолата. Тук имаме два начина, по които можем да обработим входа. Първият е чрез прочитането на целия ред с командата Console.ReadLine() и достъпването на всеки един символ (char) от реда чрез foreach цикъл. Вторият е чрез прочитане на входа символ по символ чрез командата Console.Read() и обработване на всеки символ.
## Текст след поправката
Обработване на входа

Входните данни се състоят от точно един ред от конзолата. Тук имаме два начина, по които можем да обработим входа. Първият е чрез прочитането на целия ред с командата Console.ReadLine() и достъпването на всеки един символ (char) от реда чрез foreach цикъл. Вторият е чрез прочитане на входа символ по символ чрез командата Console.Read() и обработване на всеки символ.

**Comment by vncpetrov** [comment]
Може, но не виждам къде е неяснотата?
Оправено е. [42fee3c62cf8c14020f7a36767be13b02b0cf446](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/42fee3c62cf8c14020f7a36767be13b02b0cf446)
