### ISSUE TITLE
Грешка при форматирането на текста

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#158]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md
## Описание
[ASCII кода на нашия символ] - [ASCII кода на символа0] = [цифрата, която репрезентира символа]
Защо 0 във този текст не е в сиво както околния текст?
## Текущ текст
Ако символът е цифра между 0 и 9. Но как можем да проверим това? Как можем да проверим дали символът ни е цифра? Тук идва на помощ ASCII кодът на символа, чрез който можем да използваме следната формула: [ASCII кода на нашия символ] - [ASCII кода на символа0] = [цифрата, която репрезентира символа]. Ако резултатът от тази проверка е между 0 и 9, то тогава нашият символ наистина е число.

**Comment by vncpetrov** [comment]
Fixed.  [b8ca71d71772fa9e228f6ba8563933e7636be2c2](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/b8ca71d71772fa9e228f6ba8563933e7636be2c2)
