### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#159]
Сори за недоописания формат, но получих грешката по мейла:

![image](https://cloud.githubusercontent.com/assets/1689586/26318961/c2adc91e-3f25-11e7-88c0-3bb5a03ebeae.png)

**Comment by udarensamolet** [comment]
Fixed with [be7ae59](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/be7ae597b7fdb0e1ceba6a14f9777746f95de2d0).
