### ISSUE TITLE
Да се ползват правилни Heading размери

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#164]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations-exam-problems.md

## Описание
Ползвани са неправилни размери на заглавията:
![image](https://cloud.githubusercontent.com/assets/1689586/26354768/b9b58ea6-3fce-11e7-8bcb-2a0662d8f8fd.png)

Заглавията винаги се правят така:
 - h1 - заглавие на главата
 - h2 - раздели в главата
 - h3, h4 - под-раздели във всеки раздел / подраздел

## Текущ текст
H1, H4, H5

## Текст след поправката
H1, H2, H3

**Comment by vncpetrov** [comment]
Fixed.
