### ISSUE TITLE
Неяснота за типа на входни данни

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#168]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations-exam-problems.md
## Описание
Неяснота за типа на входни данни
2 числа -  Не става ясно от тип doble или int??
## Текущ текст
Входни данни
От конзолата се четат 2 числа, по едно на ред: l (дължина в метри) и w (широчина в метри). 

## Текст след поправката
От конзолата се четат 2 реални числа, по едно на ред: l (дължина в метри) и w (широчина в метри).

**Comment by udarensamolet** [comment]
Задачата е изпитна, нарочно не е упоменато.
