### ISSUE TITLE
Пропуснат space

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#169]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations-exam-problems.md
## Описание
Пропуснат space при набиране на текста.
 ## Текущ текст
плочка е широка 5 м. и дълга 4 м. и има площ = 20кв.м. Площта, която
## Текст след поправката
плочка е широка 5 м. и дълга 4 м. и има площ = 20 кв.м. Площта, която

**Comment by udarensamolet** [comment]
Fixed with [b92f970](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/b92f970108c4e146cba0d21e6babba238e5f3bde).
