### ISSUE TITLE
Стратегия за бранчове и мърджове

### ISSUE THREAD

**Issue by mchaov** [SoftUni/Programming-Basics-Book-CSharp-BG#17]
Git Flow?

друга?

В примерите по-долу давам стандартни стратегии за разработка на софтуер със сорс контрол.

**1 – No Branches**
Book
└ Master
    └ Source

**2 – Branch for Chapter**
Book
└ Master → Main integration branch
│   └ Source
└ Chapters
      └ Chapter 1 → Release branch
               └ Source

**3 – Branch for Chapter**
Book
└ Master → Main integration branch
│   └ Source
└ Chapter → Maintenance branch container
   └ Chapter 1 → Maintenance branch
   │      └ Source
   │      └ Other Asset Folders
   └ Chapter 2 → Maintenance branch
          └ Source
          └ Other Asset Folders

**4 – Branch for Writing**
Book
└ Writing → Isolated development branch container
│     └ Chapter A → Feature branch
│     │      └ Source
│     └ Chapter B → Feature branch
│     │      └ Source
│     └ Chapter C → Feature branch
│              └ Source
│
└ Master → Main Integration branch
         └ Source

**5 – Branch per Team**
Book
└ Writing → Isolated development branch container
│     └ Group 1 → Team branch
│     │     └ Chapter A → Isolated branch for development
│     │     │         └ Source
│     │     └ Chapter B → Isolated branch for development
│     │                └ Source
│     │
│     └ Group 2 → Team branch
│            └ Chapter A → Isolated branch for development
│            │          └ Source
│            └ Chapter B → Isolated branch for development
│                    └ Source
│
└ Master → Main Integration branch
        └ Source

**Comment by Teodor92** [comment]
Още си мисля, че е добра идея да има branching.

**Comment by nakov** [comment]
Засега оставаме без branches, понеже голяма част от екипа не са ползвали такова нещо и ще им в трудничко. Може да променим стратегията по-късно.

**Comment by mchaov** [comment]
No branches също е стратегия :)
