### ISSUE TITLE
Снимка и текст едно под друго при написан код.Видима разлика

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#170]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations-exam-problems.md
## Описание
Първото е снимка другото е текст със фон.**Има забележима разлика между двете.**  
## Текущ текст
В условието на задачата не е зададено специално форматиране или закръгляне на резултата, следователно трябва просто да изчислим изхода и да го отпечатаме на конзолата.

Нека обърнем внимание на нещо, което важи за всички задачи от този тип: разписано по този начин, решението на задачата е доста подробно. Тъй като условието като цяло не е сложно, бихме могли на теория да напишем един голям израз, в който директно след получаване на входните данни да сметнем изходната стойност. Напр., такъв израз би изглеждал ето така:

double euro = (bitcoins * 1168 + yuans * 0.15 * 1.76) / 1.95 - 
  ((bitcoins * 1168 + yuans * 0.15 * 1.76) / 1.95 * commission);
Този код би дал правилен резултат, но се чете трудно. Няма да ни е лесно да разберем какво прави и дали съдържа

**Comment by udarensamolet** [comment]
Fixed.
