### ISSUE TITLE
Неяснота свързана със cw + Tab + Tab

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#172]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-10-tricks-and-hacks.md
## Описание
1.Трябва да е Console.WriteLine();  а не Console.WriteLine(...); в този случаи.
2.Има една кавичка повече след [cw + Tab + Tab]
## Текущ текст
Примерно при изписването на [cw + Tab + Tab]" се генерира кодът Console.WriteLine(...);:
## Текст след поправката
Примерно при изписването на [cw + Tab + Tab] се генерира кодът Console.WriteLine();:

**Comment by vncpetrov** [comment]
Fixed. [95245387279445228d71113adb5b05574b0209ae](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/95245387279445228d71113adb5b05574b0209ae)
