### ISSUE TITLE
Правописни грешки

### ISSUE THREAD

**Issue by sevgin0954** [SoftUni/Programming-Basics-Book-CSharp-BG#174]
Защо не минете цялата книга през някаква програма за правописни грешки 
 http://www.jabse.com/pravopis/ или през word

**Comment by OgnyanPenkov** [comment]
Програмата хваща правописни грешки но не може да хване смисловите грешки, така че си има нужда от редактори да я проверяват.

**Comment by sevgin0954** [comment]
Не съм и казвал обратното просто прочетох набързо първите няколко глави и открих 3-4 правописни грешки.Примерно "Инициализационfен блок"  в Глава 5 , "имплементацияте", "взаимосвързани" в Предговор  сигурно има и още

**Comment by udarensamolet** [comment]
Цитираните правописни грешки са коригирани, ако откриете и други, пуснете issue-та и за тях.
