### ISSUE TITLE
Грешен линк за faceboook страницата

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#175]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-00-preface.md
## Описание
Линка със facebook страницата не работи
## Текущ текст
Книгата си има и официална Facebook страница, от която може да следите за новини около книгите от поредицата "Основи на програмирането", нови издания, събития и инициативи:

fb.com/IntroProgrammingBooks

**Comment by vncpetrov** [comment]
При мен работи.

**Comment by nakov** [comment]
И при мен работи.
