### ISSUE TITLE
Правописна грешка трябва да е намалявам

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#179]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-04-complex-conditions-exam-problems.md
## Описание
https://kaksepishe.com/namalyavam/
Как се пише: намалявам или **намалям**?
## Текущ текст
През май, при повече от 14 нощувки, **намаляме** цената на студиото с 30% (50 – 15 = 35), а на апартамента – с 10% (65 – 6.5 =58.5).
## Текст след поправката
През май, при повече от 14 нощувки, намаляваме цената на студиото с 30% (50 – 15 = 35), а на апартамента – с 10% (65 – 6.5 =58.5).

**Comment by udarensamolet** [comment]
Fixed with [9994b39](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/9994b39e5fbdd430e44d504b4da873d26a15dac0).
