### ISSUE TITLE
Използване на еднакъв code style за всички примери

### ISSUE THREAD

**Issue by Teodor92** [SoftUni/Programming-Basics-Book-CSharp-BG#18]
Хубаво е да се дискутира унифицирането на code style-a за всички примери с някой tool - примерно Style Cop.

**Comment by nakov** [comment]
Аз съм съгласен. Обаче с default настройките ли?
Те са малки примерчетата по 10-20 реда кода, едва ли ще има кво толкова да хване StyleCop.

**Comment by tatarski** [comment]
Може някой да даде парче код съдържащо достатъчно примери, за да се ориентираме.

**Comment by Teodor92** [comment]
Well, може да хване следните неща:
- именуване
- използване на braces
- ненужен white space
и т.н.

Може да се ползва [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) NuGet пакета. Default-ните предупреждения са предостатъчни.

Единствените изиквания са VS 2015+

**Comment by nakov** [comment]
ОК, нека ползваме предложеното от Теодор.
