### ISSUE TITLE
чертаене vs чертане

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#180]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-05-loops.md
## Описание
чертаене vs чертане
## Текущ текст
интерактивен онлайн инструмент за **чертаене** с костенурка
## Текст след поправката
интерактивен онлайн инструмент за чертане с костенурка

**Comment by udarensamolet** [comment]
Fixed with [a048ada](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/a048adaf10845bdc85338ae0792d1641e4208d17).
