### ISSUE TITLE
чертаене vs чертане 

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#182]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-06-drawing-at-the-console-exam-problems.md
## Описание
чертаене vs чертане 
## Текущ текст
За да можем да използваме отново създадените променливи при **чертаенето** на дръжката на брадвата, трябва да 
## Текст след поправката
За да можем да използваме отново създадените променливи при чертането на дръжката на брадвата, трябва да

**Comment by udarensamolet** [comment]
Fixed with [7d5e729](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/7d5e729720a8c200168d5cc03502107428dbf5d3).
