### ISSUE TITLE
неяснота - посказки    подсказки

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#183]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-06-drawing-at-the-console.md
## Описание
посказки - руска дума трябва да е може би подсказки.Не може ли някои по лесна дума да сложим?
## Текущ текст
Насоки и **посказки**

Как работи примерът? Инициализира се цикъл с променлива i = 1, която се увеличава на всяка итерация на цикъла, докато е по-малка или равна на 10. Така кодът в тялото на цикълa се изпълнява 10 пъти. В тялото на цикъла се печата на нов ред в конзолата new string('*', 10), което създава низ от 10 звездички.

**Comment by udarensamolet** [comment]
Fixed with [6ecf7fd](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/6ecf7fd3a5822419e47c94663eaa868562456cc8).
