### ISSUE TITLE
Грешка Отпечатвме

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#184]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-06-drawing-at-the-console.md
## Описание
Отпечатвме
## Текущ текст
използваме два отделни цикъла, като оставяме на читателя сам да намери зависимостта между n и променливите на циклите. За първия цикъл може да използваме следните насоки: 

**Отпечатвме** n-row интервала. 
## Текст след поправката
използваме два отделни цикъла, като оставяме на читателя сам да намери зависимостта между n и променливите на циклите. За първия цикъл може да използваме следните насоки: 

Отпечатваме n-row интервала.

**Comment by udarensamolet** [comment]
Fixed with [14e08d1](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/14e08d18c1ad2a0e09cba08fa23cffceb18225d4).
