### ISSUE TITLE
Грешка изпозлва

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#185]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-06-drawing-at-the-console.md
## Описание
 изпозлва     използва
## Текущ текст
нашият случай 1.5f ще стане 2. (int) се **изпозлва**, за да може да трансформираме типа обратно в Integer.
## Текст след поправката
нашият случай 1.5f ще стане 2. (int) се използва, за да може да трансформираме типа обратно в Integer.

**Comment by udarensamolet** [comment]
Fixed with [2e78201](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/2e78201b9c0d8b784aeb70a97ba0adbe70de7a7e).
