### ISSUE TITLE
грешка оеринтирате

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#186]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-06-drawing-at-the-console.md
## Описание
оеринтирате - ориентирате    
## Текущ текст
За да се **оеринтирате** по-добре в проекта, може да си помогнете с картинката от Visual Studio по-долу: 
## Текст след поправката
За да се ориентирате по-добре в проекта, може да си помогнете с картинката от Visual Studio по-долу:

**Comment by udarensamolet** [comment]
Fixed with [fc023e6](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/fc023e6815be068e165cf140d768aad61db71bb0).
