### ISSUE TITLE
грешка конструкци

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#187]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-07-complex-loops-exam-problems.md
## Описание
**конструкци**    консрукции
## Текущ текст
Вече научихме как може да изпълним даден блок от команди повече от веднъж използвайки for цикъл. В предходната глава разгледахме още няколко циклични **конструкци**, които биха ни помогнали при решаването на по-сложни проблеми, а именно: 

## Текст след поправката
Вече научихме как може да изпълним даден блок от команди повече от веднъж използвайки for цикъл. В предходната глава разгледахме още няколко циклични консрукции, които биха ни помогнали при решаването на по-сложни проблеми, а именно:

**Comment by udarensamolet** [comment]
Fixed with [8f95970](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/8f95970285f9b29c9713913390aa21e77e8c78bd).
