### ISSUE TITLE
сбъсквали

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#188]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-07-complex-loops-exam-problems.md
## Описание
**сбъсквали**
## Текущ текст
С втората част също сме се **сбъсквали** - инициализиране на for цикъл. Тук има малка уловка - в условието е споменато, че числата трябва да се принтират в обратен ред
## Текст след поправката
С втората част също сме се сблъсквали - инициализиране на for цикъл. Тук има малка уловка - в условието е споменато, че числата трябва да се принтират в обратен ред

**Comment by udarensamolet** [comment]
Fixed with [4b403bb](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/4b403bb47a7b33f2b5a16493265b97d33979518f).
