### ISSUE TITLE
съставко

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#189]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-07-complex-loops.md
## Описание
**съставко**
## Текущ текст
 просто (true) или съответно **съставко** (false). 
## Текст след поправката
 просто (true) или съответно съставно (false)

**Comment by udarensamolet** [comment]
Fixed with [3aebf68](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/3aebf68388d301fb1572c498fa68768368faff9b).
