### ISSUE TITLE
Темата "Подготовка за практически изпит" няма слайдове

### ISSUE THREAD

**Issue by tonyozhelev** [SoftUni/Programming-Basics-Book-CSharp-BG#19]
Записах се да пиша за "Подготовка за практически изпит", но темата няма слайдове. Прегледах една част от предните инстанции на курса и в този ден се решава някой от миналите изпити. Прегледах и упражненията от последната инстанция на курса и никъде не са давани задачи от изпитите на 20ти Ноември. Ако е ОК ще пиша за единия от тях и така ще има 2 решени изпита в книгата.

**Comment by yani-valeva** [comment]
По принцип няма презентация за подготовките. Подбират се задачи и се обясняват и понеже са различни няма слайдове. Не знам дали ще ти е полезно, но мога да ти дам линк от моята инстанция на курса. Тогава бяха подбрали от всеки тип задачи по две.  https://softuni.bg/trainings/1439/programming-basics-august-2016

**Comment by tonyozhelev** [comment]
Еми, да, пак се решават задачи подобни на изпита. Принципно тези дето си ги дала съм ги решавал и има доста интересни, но мисля, че ще е по-добре да се вземе някой по-скорошен изпит. Разликата е, че твотите са по-скоро математически тип задачи, а на сегашните изпити задачите са тип историйка с проблем и ще е добре да се представят на читателите подобни на изпита задачи, за да могат да свикнат с условията. Затова и се насочих към някой от по-скорошните изпити. Така или иначе, ще почна чак в понеделник да пиша, така че ако някой друг има предложения, добре дошъл е да се включи :)
