### ISSUE TITLE
Пресмятанет

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#190]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-08-exam-preparation-part-2.md
## Описание
Пресмятанет
## Текущ текст
**Пресмятанет** на процентите, както и следващите изминати разстояния, извършваме по следния начин: 
## Текст след поправката
Пресмятането на процентите, както и следващите изминати разстояния, извършваме по следния начин:

**Comment by udarensamolet** [comment]
Fixed with [19fd4aa](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/19fd4aaebc6bdc8a5d7f10f45fe814cd53d1bc86).
