### ISSUE TITLE
едноцифрени (например 01, 08, 12).

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#191]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-08-exam-preparation.md
## Описание
12 не е едноцифрено
## Текущ текст
0 дни, февруари има 28 дни, а останалите имат по 31 дни. Месеците да се отпечатат с водеща нула, когато са **едноцифрени (например 01, 08, 12).** 
## Текст след поправката
0 дни, февруари има 28 дни, а останалите имат по 31 дни. Месеците да се отпечатат с водеща нула, когато са едноцифрени (например 01, 05, 08).

**Comment by udarensamolet** [comment]
Fixed with [0e813fe](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/0e813fed5aca7136b48f3996367c7ff8539aed59).
