### ISSUE TITLE
Грешка - излишно долно тире

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#192]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-09-problems-for-champions.md
## Описание
излишно долно тире
## Текущ текст
а подредени в ASCII таблицата. Изразът 'а' + i ще ни даде резултата 'a', ако i е равно на 0, 'c', ако i е равно на 2 и т.н.**_**
## Текст след поправката
а подредени в ASCII таблицата. Изразът 'а' + i ще ни даде резултата 'a', ако i е равно на 0, 'c', ако i е равно на 2 и т.н.

**Comment by udarensamolet** [comment]
Fixed with [33ab648](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/33ab648efb9f6a8a0438b42fcf978a456757c444)
