### ISSUE TITLE
По-малки screenshots

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#193]
В глава 1 да се смени следната картинка с по-малка:

https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/raw/master/assets/chapter-1-images/01.Hello-csharp-03.png

Картинката включва излишно празно място, което на телефон ще доведе до нечетим текст:

![image](https://cloud.githubusercontent.com/assets/1689586/26755813/0ae7c582-489e-11e7-9584-baf0300d3790.png)

Да се вземе нов screenshot, в който Visual Studio екранът е намален, за да няма излишно празно място. Това празно място не носи никаква стойност на читателя на книгата, но пък заради него картинката е по-голяма и на телефон ще доведе до нечетимо малък шрифт!

**Comment by nakov** [comment]
Ето пример как може да се направи картинката:

![image](https://cloud.githubusercontent.com/assets/1689586/26755829/5c310336-489e-11e7-8d11-1fec4f52926d.png)

**Comment by udarensamolet** [comment]
done
