### ISSUE TITLE
По-добра картинка

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#196]
В глава 1 тази картинка може да се обработи, за да е по-малка. Сега картинката съдържа твърде много празно място, което трябва да се изреже:

![image](https://cloud.githubusercontent.com/assets/1689586/26756021/32862e0e-48a2-11e7-80e1-ccee8119d114.png)

Целта отново е по-добър изглед на телефон. Ако картинката е излишно широка, на телефон ще се свие и текстът ще стане нечетим.

**Comment by udarensamolet** [comment]
Fixed
