### ISSUE TITLE
Замяна на "ударено и" с "й"

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#197]
Да се намерят и заменят повсеместно всички "**ударено и**" с "**й**". Наясно съм кое е по-правилно в българския език, но GitBook е на друго мнение и нямаме избор, нали?

![image](https://cloud.githubusercontent.com/assets/1689586/26756622/88c34f6a-48af-11e7-963e-b45f88d210e4.png)

Ако намерите по-умно решение, може да се приложи то. При всички положения сега ударените "и" се визуализират грешно и това трябва да се поправи!

**Comment by nakov** [comment]
В GitHub няма проблем, но в GitBook има и трябва да се поправи.

Може да се направи глобален search в сорс кода с някакъв умен текстов редактор, за да сме сигурни, че сме оправили проблема навсякъде.

**Comment by nakov** [comment]
Да се добави и една бележка в Wiki страницата по темата с удареното "и".

**Comment by udarensamolet** [comment]
Не можем да визуализираме проблема. 
![image](https://cloud.githubusercontent.com/assets/5997265/26782287/778a1ee8-49fb-11e7-8e4d-970283013b46.png)
Да го променим ли все пак?

**Comment by nakov** [comment]
Разгадах проблема: чупи се само ако сменим шрифта на "Serif" от тука:

![image](https://cloud.githubusercontent.com/assets/1689586/26799341/d5c2ecf0-4a3d-11e7-9974-2bb73c8c7b79.png)

В PDF също се визуализира правилно.

Можем да забравим за проблема. Явно е само при другия шрифт (Serif).

Ако не сте бутали, можем да затворим този проблем.

**Comment by udarensamolet** [comment]
Не сме коригирали нищо.
