### ISSUE TITLE
bug in chapter 2

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#198]
## Линк към файла
 Глава 2
## Описание

Картинката съдържа 3 въведени реда, а трябва да са 4 реда:
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/assets/chapter-2-images/rectangleAreaExample.jpg

**Comment by vncpetrov** [comment]
Fixed. [image](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/assets/chapter-2-images/rectangleAreaExample.jpg)
