### ISSUE TITLE
Несъотвествие между линк и картинка със същия линк

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#199]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
Несъотвествие между линк и картинка със същия линк
## Текущ текст
Тестване в Judge системата
Тествайте решението си тук: https://judge.softuni.bg/Contests/Practice/Index/504#0. Трябва да получите 100 точки (напълно коректно решение):

https://judge.softuni.bg/Contests/Practice/Index/504#0.   Линк в описанието 
https://judge.softuni.bg/Contests/Practice/Index/151#0.   Линк на снимката 
## Текст след поправката
Да се смени снимката

**Comment by vncpetrov** [comment]
Fixed.
