### ISSUE TITLE
Шаблон за "Изпитни задачи: Х"

### ISSUE THREAD

**Issue by rextor92** [SoftUni/Programming-Basics-Book-CSharp-BG#20]
Привет,

Всички глави, покриващи изпитни задачи върху конкретна тема, би следвало да имат един и същ шаблон. Броят задачи може да се различава, но бих искал да обсъдим следните:

- Брой задачи с подробно обяснен код?
- Брой задачи с частичен код и подробни подсказки по стъпки? Като допълнение към горното, остатъка от кода замъглен ли ще бъде или с //TODO коментари
- Останалите задачи - само с подсказки - стъпки, които трябва да се изпълнят, без никакъв код?

За самите задачи предлагам:

- Да си направим собствено репозитори в гитхъб и да качим всички решения за конкретната глава
- Да архивираме проект и да го качим в OneDrive / GoogleDrive / dropbox / etc

След което да сложим линк в края на главата - този линк ще бъде само работен и ще бъде премахнат в края на работата, но ще улесни максимално редакторите и Наков (или който създава contest @ judge)

**Comment by nakov** [comment]
Мисля, че говорихме **по 3 изпитни задачи** да има след всяка от 6-те теми, включени в изпита, но не виждам проблем да има и повече. Ето и предложение:
- Първата задача - детайлни инструкции + почти цялостно решение, разписано стъпка по стъпка (80-90% готово) с частично замъглен код на места, за да няма copy/paste
 - Втора задача - по-малко инструкции и частично разписано по стъпки решение (50-70% готово)
 - Трета задача - още по-малко инструкции и разписани само основните стъпки и насоки (30-50% готово)

Кодът да се дава като screenshots от Visual Studio (с бялата тема), за да няма copy/paste.

**Comment by tonyozhelev** [comment]
Хубаво е да се разберем и какъф font size ще ползваме, за да не се получи така, че всяка глава да има различен размер на поставения в нея код. Аз съм със default настройки на VS и 125% zoom ми се струва добре като размер.

**Comment by nakov** [comment]
Подкрепям:
 - светла тема във VS
 - стандартни настройки във VS
 - font-size: стандартен + 125% zoom
