### ISSUE TITLE
Picture problem - inches vs Inches

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#200]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
На първата картинка със кода е написано **inches**
На двата изходни екрана е написано **Inches**

## Текущ текст
Следва да напишем кода на програмата:

Стартираме програмата с [Ctrl+F5]:

Изненада! Какво става? Програмата не работи правилно… Всъщност това не е ли предходната програма? Във Visual Studio текущият активен проект в един solution е маркиран в получерно и може да се сменя:

Превключваме обратно към проекта “Inches-to-Centimeters” и го стартираме с [Ctrl+F5]:

Превключването между проектите е много лесно, нали? Просто избираме файла със сорс кода на програмата, кликваме го два пъти с мишката и при стартиране тръгва програмата от този файл.

Да тестваме с дробни числа, например с 2.5:

**Comment by vncpetrov** [comment]
Fixed. [a38e83a6f12857795d510f3d4b4b76ef54e762a2](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/a38e83a6f12857795d510f3d4b4b76ef54e762a2)
