### ISSUE TITLE
 Неяснота кръг/окръжност

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#201]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
Неяснота **кръг/окръжност** .Последно на кое трябва да пресметнем лицета на кръга или на окръжността? 
## Текущ текст
Напишете програма, която чете от конзолата число r и пресмята и отпечатва лицето и периметъра на кръг/окръжност с радиус r.

**Comment by udarensamolet** [comment]
Окръжността е кривата, която е образувана от множество точки в равнина. При нея може да се изчисли само периметър. Кръга е множеството точки във вътрешността на окръжността, стоящи на разстояние от центъра, което е по-малко или равно на радиуса. При кръга може да се изчисли само лице. Това е и причината да е написано по този начин.
