### ISSUE TITLE
Изпусната нула.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#202]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
до 2 знака след десетичния знак
Трябва да бъде написано **22.10**  а не 22.1 както е сега  

## Текущ текст
до 2 знака след десетичния знак. Ето няколко примера:

Примерен вход и изход

Вход	Изход
25	       77
0	        32
-5.5	        **22.1**
32.3	        90.14

**Comment by udarensamolet** [comment]
Използвайки `Math.Round(...)` програмата връща описаните стойности като изход по начина, по който са изписани в таблицата.
