### ISSUE TITLE
Отново изпуснати нули

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#203]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
**262.5**     262.50
**300**        300.00
## Текущ текст
Напишете програма, която чете от конзолата страна и височина на триъгълник и пресмята неговото лице. Използвайте формулата за лице на триъгълник: area = a * h / 2. Закръглете резултата до **2 знака след десетичния знак** използвайки Math.Round(area, 2).

Примерен вход и изход

Вход	Изход
20 
30	Triangle area = **300**
15 
35	Triangle area = **262.5**

**Comment by udarensamolet** [comment]
#202
