### ISSUE TITLE
2 знака или 2 цифри

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#204]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
На една е съща страница се ползват две понятия за едно и също нещо. 2 знака или 2 цифри
## Текущ текст
Потърсете в Интернет подходяща формула, с която да извършите изчисленията. Закръглете резултата до **2 знака** след десетичния знак. Ето няколко примера:

ране, входна валута и изходна валута. Изходът е едно число – преобразуваната сума по посочените по-горе курсове, закръглен до **2 цифри** след десетичната точка.

**Comment by udarensamolet** [comment]
Fixed with [aaf495d2](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/aaf495d2459a64a06aecaa4d9e519f5db2c94704).
