### ISSUE TITLE
inches e с малка буква проблем

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#205]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
На снимката която е между този текст inches e с малка буква
## Текущ текст
Сега отново стартираме програмата, както обикновено с [Ctrl+F5]. Този път ще се стартира текущата отворена програма, която преобразува инчове в сантиметри. Изглежда работи коректно:

Сега да превключим към преходната програма (лице на квадрат). Това става с двоен клик на мишката върху файла Program.cs от предходния проект “Square-Area” в панела [Solution Explorer] на Visual Studio:

**Comment by vncpetrov** [comment]
Fixed.
