### ISSUE TITLE
Картинки без рамка в глава 4

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#208]
В глава 4 има няколко картинки без рамка. Да им се добави лека сивичка рамка 1px:
- https://csharp-book.softuni.bg/assets/chapter-4-images/14.Point-in-rectangle-gui-01.png
- https://csharp-book.softuni.bg/assets/chapter-4-images/14.Point-in-rectangle-gui-02.png
- https://csharp-book.softuni.bg/assets/chapter-4-images/14.Point-in-rectangle-gui-03.png

**Comment by udarensamolet** [comment]
Fixed with [2414c69](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/2414c690ccfd65eb20315913556062d4008cc354).
