### ISSUE TITLE
Обновяване от gitbook към github

### ISSUE THREAD

**Issue by ROSSFilipov** [SoftUni/Programming-Basics-Book-CSharp-BG#21]
Има някакъв проблем при обновяването от gitbook към github. Промените не се отразяват тук. Възможно е да нещо свързано с права.

**Comment by ChrisPam** [comment]
Нали в gitbook не се разрешава повече от 5 authors. Според мен точно това е проблема

**Comment by ROSSFilipov** [comment]
Предполагам, че може да се извърши ръчно прехвърляне от някой, който вече е автор.

**Comment by Teodor92** [comment]
Алтернативно, може да редактираме директно в GitHub. Повечето IDE-та подържат markdown, така че не би трябвало да е проблем.

**Comment by nakov** [comment]
Засега редактирайте директно в GitHub. Ще ползваме GitBook само катo билд система.

**Comment by nakov** [comment]
Обновяването е автоматично. Пишете си MD файловете в GitHub, а те се качват автоматично в GitBook и след няколко минути се публикуват live.

**Comment by nakov** [comment]
Дори за open-source проекти то GitBook искат пари при повече от 5 team members. Не мисля, че има нужда от това. Хайде да пробваме да си пишем книгата през GitHub.
