### ISSUE TITLE
inches с малка буква

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#210]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
Снимката която е отдолу с грешката се вижда на първи ред inches с малка буква
## Текущ текст
Ако програмата очаква десетична точка и бъде въведено число с десетична запетая или обратното (бъде въведена десетична точка, когато се очаква десетична запетая), ще се получи следната грешка:

**Comment by vncpetrov** [comment]
Fixed.
