### ISSUE TITLE
Точки в текста

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#211]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
Какви са тези точки в текста?
## Текущ текст
Подреждаме следните UI контроли във формата: • NumericUpDown с име numericUpDownAmount – ще въвежда сумата за конвертиране •	Label с име labelResult – ще показва резултата след конвертиране •	Още два Label компонента, служещи единствено за статично изобразяване на текст Графичният редактор за потребителски интерфейс може да изглежда по подобен начин:

**Comment by udarensamolet** [comment]
Fixed with [a776d7a](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/a776d7adc5d71c3153f6c37668174853551890b4).
