### ISSUE TITLE
Въпросче

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#212]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание
На снимката отдолу на проекта на задачата на Greeting има червено кръгче и червено тикче.
При мен нямя такива.**Трябва ли да го има на снимката**?(Знам че е git клиента в Visual Studio)

## Текущ текст
Да се напише програма, която чете от конзолата име на човек и отпечатва Hello, <name>!, където <name> е въведеното преди това име.

Насоки и подсказки

Първо създаваме нов C# конзолен проект с име “Greeting” в решението “Simple-Calculations”:

**Comment by udarensamolet** [comment]
Fixed
