### ISSUE TITLE
Неяснота броейки

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#214]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-10-methods.md
## Описание
Това не е художествена литература че да се налага да ползваме деепричастие **броейки**.
Можем да го напишем започваме да броенето от 1 от посоката е от дясно на ляво.
Или да го пропуснем както е понадолу в текста.

## Текущ текст
Да се напише метод FindNthDigit(number, index), който получава число и индекс N като параметри и печата N-тата цифра на числото (**броейки от дясно на ляво, започвайки от 1**). След това, резултатът да се отпечата на конзолата.

Примерен вход и изход

Вход	Изход	Вход	Изход	Вход	Изход
83746
2	4	93847837
6	8	2435
4	2
Насоки и подсказки

За да изпълним алгоритъма, ще използваме while цикъл, докато дадено число не стане 0. На всяка итерация на while цикъла ще проверяваме дали настоящият индекс на цифрата не отговаря на индекса, който търсим. Ако отговаря, ще върнем като резултат цифрата на индекса (number % 10). Ако не отговаря, ще премахнем последната цифра на числото (number / 10). Трябва да следим коя цифра проверяваме по индекс (**от дясно на ляво, започвайки от 1**). Когато

**Comment by udarensamolet** [comment]
Fixed with [bfc2f74](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/bfc2f740de438673d378f6915a57d07f7cce60af).
