### ISSUE TITLE
лека структура от данни

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#215]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-10-methods.md
## Описание
Започва да се заражда въпроса кое е лека структура от данни и кое тежка структура от данни?
**Трябва ли да пишем тук** дали една структура от данни е лека или тежка?
## Текущ текст
Накратко типът ValueTuple представлява **лека структура от данни**, позволяваща временното съхранение на множество стойности
## Текст след поправката
Накратко типът ValueTuple представлява структура от данни, позволяваща временното съхранение на множество стойности

**Comment by nakov** [comment]
Бих го написал "Накратко типът ValueTuple представлява съвкупност от две стойности", без да уточнявам дали е структура от данни. Един термин по-малко,а текстът си остава разбираем и със същия смисъл.

**Comment by vncpetrov** [comment]
Коригирах го. [9dd6b7ccc1eed5037e3f00d0538cfacaa631f27e](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/9dd6b7ccc1eed5037e3f00d0538cfacaa631f27e)
