### ISSUE TITLE
2>

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#216]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-10-methods.md
## Описание
2>  може би трябва да е 2
## Текущ текст
Пример: по-голямата от две стойности

Като входни данни са дадени две стойности от един и същ тип. Стойностите могат да са от тип int, char или string. Да се създаде метод GetMax(), който връща като резултат по-голямата от двете стойности.

Примерен вход и изход

Вход	Изход	Вход	Изход	Вход	Изход
int
**2>**
16	16	char
a
z	z	string
Ivan
Todor	Todor
Насоки и подсказки

**Comment by udarensamolet** [comment]
Fixed with [780e287](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/780e2871009c57a5ee2f2b743df4f9c83a816f3f).
