### ISSUE TITLE
Неяснота и т.н.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#217]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-10-methods.md
## Описание
Откъде това **и т.н.** като ние даваме пример само със 3 числа 111, 814, 919
## Текущ текст
Третият специален случай е когато числото, формирано от последните две цифри на входното число, е по-голямо от 10 и по-малко от 20 (напр. 111, 814, 919). В този случай отпечатваме "one-hundred and eleven", "eight-hundred and fourteen", "nine-hundred and nineteen" **и т.н.**
## Текст след поправката
Третият специален случай е когато числото, формирано от последните две цифри на входното число, е по-голямо от 10 и по-малко от 20 (напр. 111, 814, 919). В този случай отпечатваме "one-hundred and eleven", "eight-hundred and fourteen", "nine-hundred and nineteen" .

**Comment by udarensamolet** [comment]
Fixed with [83b9d9a](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/83b9d9ab64b079519a7f8ebb19a371ecfd38c3bf).
