### ISSUE TITLE
Файлове към упражненията за уеб проект в глава 7

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#219]
## Линк към файла

Глава 7: https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-07-complex-loops.md

## Описание

В упражнението за уеб приложение се изисква да се копират разни картинки от файловете с упражнението в ASP.NET MVC проекта. Да де, обаче това е в курса Programming Basics. В книгата този ZIP файл с ресурсите липсва. Да се сложи като актив в `/assets` и да се линкне, за да може всеки читател да го изтегли!

**Comment by udarensamolet** [comment]
Done
