### ISSUE TITLE
Несъотвествие между две снимки

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#220]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md
## Описание

Enter your name :  липсва на снимка със кода но присъства като се пусне програмата. 

## Текущ текст
Следва да напишем кода на програмата. Ако се затруднявате, може да ползвате примерния код по-долу:

Стартираме програмата с [Ctrl+F5] и я тестваме дали работи:

**Comment by vncpetrov** [comment]
Fixed. [6eaec0c6d960448718b22f71423e](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/ac4f350ef9576eaec0c6d960448718b22f71423e)
