### ISSUE TITLE
Корекции по глава 01

### ISSUE THREAD

**Issue by MayaLekova** [SoftUni/Programming-Basics-Book-CSharp-BG#221]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md

## Описание

1. В [началото на главата](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md#%D0%9F%D0%B8%D1%81%D0%B0%D0%BD%D0%B5-%D0%BD%D0%B0-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B5%D0%BD-%D0%BA%D0%BE%D0%B4) се споменава секцията `Main(string[] args)`, а по-надолу в същата глава при [типичните грешки](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md#%D0%A2%D0%B8%D0%BF%D0%B8%D1%87%D0%BD%D0%B8-%D0%B3%D1%80%D0%B5%D1%88%D0%BA%D0%B8-%D0%B2-c-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8%D1%82%D0%B5) същата е спомената като "тялото на `Main()` метода". На този етап не е обяснено нито понятието "метод", нито "тяло на функция".
1. По-надолу [в първата задача](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md#%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0-%D0%BA%D0%BE%D0%BD%D0%B7%D0%BE%D0%BB%D0%BD%D0%B0-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B0-expression) се използва символът "*" за пресмятане на числен израз. Никъде по-рано не се споменава, че това е знак за умножение.
1. Още по-нататък [в следващата задача](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md#%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0-%D1%87%D0%B8%D1%81%D0%BB%D0%B0%D1%82%D0%B0-%D0%BE%D1%82-1-%D0%B4%D0%BE-20) очакваният резултат от изхода на кода е 
```
1
2
...
20
```
Предполага ли се четящият сам да се ориентира, че многоточието замества липсващи редове?

Обща препоръка: има правописни грешки, които лесно могат да бъдат оправени с автоматичен spell checker.

**Comment by vncpetrov** [comment]
2. В числен израз какво друго може да означава символът "*"? 
3. Мисля, че всеки, които е прочел условието и обясненията по задачата, ще разбере, че даденият изход е в съкратен вариант.

Относно правописните грешки - минавали сме по няколко пъти всяка глава през spell checker, така че, ако има грешки моля да ги докладвате.

**Comment by nakov** [comment]
Благодарим за забележките. По точки 2 и 3 Венци е отговорил и подкрепям неговото мнение.

По точка 1: съгласен съм и нанесох корекции в текста.

За правописните грешки: ще се радваме да ни ги докладвате. Не е толкова лесно да се пусне spell checker за български текст в Markdown формат.
