### ISSUE TITLE
Submit бутон грешка

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#223]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md
## Описание
На снимката отгоре се вижда бутона Изпрати а не **[Submit]**.
## Текущ текст
Изпращаме решението за оценяване с бутона **[Submit]**. Системата връща резултат след няколко секунди в таблицата с изпратени решения. При необходимост може да натиснем бутона за обновяване на резултатите [refresh] в горната дясна част на таблицата с изпратени за проверка решения:

**Comment by vncpetrov** [comment]
Fixed. [a6f7867c6635261faf90a77060cc3da6f6278faf](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/a6f7867c6635261faf90a77060cc3da6f6278faf)
