### ISSUE TITLE
SoftUni Judge или SoftUni judge

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#224]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md
## Описание
*SoftUni judge** не трябва ли да бъде SoftUni Judge
## Текущ текст
Видяхме как да печатаме с Console.WriteLine(...) и как да стартираме програмата си с [Ctrl + F5]. Научихме се да тестваме кода си в **SoftUni judge**.

**Comment by vncpetrov** [comment]
Fixed. [a063c5f0f855f535fb4146a2490acdf56eeb7c04](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/a063c5f0f855f535fb4146a2490acdf56eeb7c04)
