### ISSUE TITLE
Неработещ линк "Цикли"

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#225]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md
## Описание
Неработещ линк **"Цикли"**
## Текущ текст
Как работят повторенията (циклите) в програмирането ще научим в главата **"Цикли"**, но засега приемете, че просто повтаряме някаква команда много пъти.

**Comment by vncpetrov** [comment]
Fixed. [863cee858ba1e997d8282a062e2f70579805f400](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/863cee858ba1e997d8282a062e2f70579805f400)
