### ISSUE TITLE
Как да се отваря hyperlink

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#226]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md
## Описание
Не е ли по добре да отваряме линка в NEW Tab за да може да остане отворена книгата в сегашния tab. 
## Текущ текст
. Там приложението е направено на живо стъпка по стъпка с много обяснения. Или питайте във форума на СофтУни: https://softuni.bg/forum.

**Comment by vncpetrov** [comment]
През официалния сайт на книгата (https://csharp-book.softuni.bg) линковете се отварят в нов прозорец на браузъра.
