### ISSUE TITLE
Synchronize C# and Java Chapter 04 - Complex Conditions

### ISSUE THREAD

**Issue by VKachanov** [SoftUni/Programming-Basics-Book-CSharp-BG#227]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-04-complex-conditions.md
## Описание
Consider merging the additions to the Java book back in the C# book 
## Текущ текст
for example - the ()-operator:
currently = empty
## Текст след поправката
Операторът скоби (())

Както останалите оператори в програмирането, така и операторите && и || имат приоритет, като в случая && е с по-голям приоритет от ||. Операторът () служи за промяна на приоритета на операторите и се изчислява пръв, също както в математиката. Използването на скоби също така придава по-добра четимост на кода и се счита за добра практика.

**Comment by vncpetrov** [comment]
Благодаря колега, добавих го.
