### ISSUE TITLE
Synchronize Java and C# books

### ISSUE THREAD

**Issue by VKachanov** [SoftUni/Programming-Basics-Book-CSharp-BG#228]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-04-complex-conditions.md
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-04-complex-conditions.md
## Описание
Wrong statement in condition of problem 08 - Trade Commissions
## Текущ текст
500 <= s <= 1000, 1000 <= s <= 10000
## Текст след поправката
500 < s <= 1000, 1000 < s <= 10000

**Comment by vncpetrov** [comment]
Fixed. [7437dff9699efa89b0c35752cfe4ccfc15a8cf1c](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/7437dff9699efa89b0c35752cfe4ccfc15a8cf1c)
