### ISSUE TITLE
Missing example solution for problem 01 in Chapter 04

### ISSUE THREAD

**Issue by VKachanov** [SoftUni/Programming-Basics-Book-CSharp-BG#230]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-04-complex-conditions.md
## Описание
Missing example solution for problem 01 in Chapter 04
## Текущ текст
empty
## Текст след поправката
Insert image with example solution as in Java book

**Comment by udarensamolet** [comment]
Fixed with [e45b23b](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/e45b23b08666da4f06dc7374b58f16576be27bd0).
