### ISSUE TITLE
Missing example solution for problems 11 to 13

### ISSUE THREAD

**Issue by VKachanov** [SoftUni/Programming-Basics-Book-CSharp-BG#231]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-04-complex-conditions.md
## Описание
Missing example solution for problems 11 to 13
## Текущ текст
empty
## Текст след поправката
Insert images of example solutions

**Comment by nakov** [comment]
Потвърждавам, това е пропуск в C# книгата, който не бяхме видяли.

Наистина липсват насоки, решения и примерен код (замъглен) за следните задачи:
 - 11 (Кино)
 - 12 (Волейбол)
 - 13 (Точка във фигурата)

от глава 4 (По-сложни проверки). Трябва да се добавят.

**Comment by vncpetrov** [comment]
Примерните решения са добавени.
