### ISSUE TITLE
Spaces in the image names

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#232]
На няколко места в книгата има файлове (картинки или ресурси), на които има **интервал** "` `" в името им. Да се променят имената им (да не съдържат интервал и да са номериранни както другите картинки) и да се актуализират MD файловете, които ги реферират.

В папката `Programming-Basics-Book-CSharp-BG\assets\chapter-4-images`:
 - `01.Personal Titles-02.png` --> `01.Personal-Titles-02.png`
 - `Personal Titles-01.jpg` --> `01.Personal-Titles-01.png`

В папката `Programming-Basics-Book-CSharp-BG\assets\editors`:
 - `01. editors.PNG` --> `01.Еditors.png`
 - `editors - blurred.png` --> `01.Editors-blurred.png`

Още нещо: тези файлове `\assets\editors` се ползват във Wiki-то, а не в книгата, нали?
- Значи тези файлове не са част от книгата, а са част от проекта за книгата. Тогава мястото им е в ресурсите към проекта, а не в ресурсите към книгата.
- Значи трябва всичко от `Programming-Basics-Book-CSharp-BG\assets\editors` да се премести в папката `\resources\wiki`.

**Comment by udarensamolet** [comment]
done
