### ISSUE TITLE
Неточност в една от задачите 

### ISSUE THREAD

**Issue by NasAtanasov** [SoftUni/Programming-Basics-Book-CSharp-BG#233]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-04-complex-conditions.md

Проблема е в Глава 4. По-сложни проверки. 
Задача: Пример: точка върху страна на правоъгълник.

Става въпрос за примерен изход, който сте дали: Inside/Outside
Judge приема за верен изход с интервал: Inside / Outside

**Comment by udarensamolet** [comment]
Fixed with [c8b591b](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/c8b591b027f9b09fc867be3dc48fc2e6b4172134).
