### ISSUE TITLE
Коментари по глава Методи.

### ISSUE THREAD

**Issue by Antoveravip** [SoftUni/Programming-Basics-Book-CSharp-BG#234]
Здравейте, колеги.

Успях да прегледам главата Методи. По долу съм нахвърлял няколко предимно дребни забележки, като повечето от тях не са нещо съществено, просто на мен ми напрви впечатление и затова съм ги извадил за дискусия, а не съм ги редактирал директно. Към всяка от забележките съм приложил коментар.

----------------------------------------------------------------

## Текущ текст
Всяко едно парче код, което изпълнява дадена **функция** и което сме отделили логически, може да изземе **функцията** на метода. Точно това представляват методите – парчета код, които са именувани от нас по определен начин и които могат да бъдат извикани толкова пъти, колкото имаме нужда.

## Текст след поправката
Всяко едно парче код, което изпълнява дадена **функционалност** и което сме отделили логически, може да приеме **функционалността** на метода. Точно това представляват методите – парчета код, които са именувани от нас по определен начин и които могат да бъдат извикани толкова пъти, колкото имаме нужда.

## Коментар
Като цяло смесването на "функции" и "методи" в едно изречение лично на мен не ми стои добре. Но това си е мое мнение.

----------------------------------------------------------------

## Текущ текст
Такива **функции** могат да бъдат разпечатване на даден низ на конзолата, извършване на някаква проверка, изпълнение на цикъл и **т.н.**

## Текст след поправката
Такива **действия** могат да бъдат разпечатване на даден низ на конзолата, извършване на някаква проверка, изпълнение на цикъл и **други.**

## Коментар
Освен заместването на функции с действия в конкретният контекст предлагам за промяна и "и т.н" на "други". Гледната ми точка е че се изброяват възможни различни действия на методи, на което продължението **"и т.н."** не ми се струва правилно.

----------------------------------------------------------------

## Коментар
На много места се среща думата "**наименуване**" и нейни производни. Лично мое мнение е че "**именуване**" звучи по-добре и предлагам за редакция.

----------------------------------------------------------------

## Текущ текст
Ако имаме подадени параметри в реда int и след това string, при извикването му не можем да подадем първо стойност за string и след това за int.

## Текст след поправката
Ако имаме подадени параметри в реда int и след това string, при извикването му не можем да подадем първо стойност за string и след това за int.
**Единствено можем да разменяме местата на подадените параметри ако изрично изпишем преди това името на параметъра, както ще забележим малко по-нататък в един от примерите. Това като цяло не е добра практика!**

## Коментар
Никъде не се споменава за подобна възможност за смяна на реда на параметрите, а само няколко по-реда по-надолу е даден такъв пример. Нужно е пояснение, защо и как става. Не претендирам, че съм дал най-доброто.

----------------------------------------------------------------

## Текущ текст
Следващият пример **онагледява** употребата на незадължителните параметри.

## Текст след поправката
Следващият пример **показва** употребата на незадължителните параметри.

----------------------------------------------------------------

## Текущ текст
Тъй като всеки метод отговаря за някаква част от нашия проблем, то при наименуването му трябва да вземем предвид неговата **функция**, т.е. добра практика е името да описва неговата цел. 

## Текст след поправката
Тъй като всеки метод отговаря за някаква част от нашия проблем, то при наименуването му трябва да вземем предвид неговата **функционалност**, т.е. добра практика е името да описва неговата цел. 

----------------------------------------------------------------

**Comment by vncpetrov** [comment]
Забележките са взети под внимание и са отстранени
