### ISSUE TITLE
Грешно написана голяма буква

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#235]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations-exam-problems.md
## Описание
Задача: учебна зала
Задача: зеленчукова борса
Задача: ремонт на плочки
**Задача: Парички**
Задача: дневна печалба

Защо само Парички е със главна буква всички други задачи с малка буква?

## Текст след поправката
Задача: парички

**Comment by udarensamolet** [comment]
Fixed with [8edc82c](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/8edc82cf46f3f1c51a6c50e5c56d851ec6bfe6cb).
