### ISSUE TITLE
Грешно написана главна буква.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#236]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-01-first-steps-in-programming.md
## Описание
Задача: числата от 1 до 20
**Задача: Триъгълник от 55 звездички**
Задача: лице на правоъгълник
 Задача: квадрат от звездички

Защо само **Триъгълник** от 55 звездички започва с главна буква?
## Текст след поправката
Задача: триъгълник от 55 звездички

**Comment by udarensamolet** [comment]
Fixed with [e6e2f906](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/e6e2f906223709ec7961051849c9cec0796c28fe).
