### ISSUE TITLE
Правописна грешка.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#237]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-03-simple-conditions.md
## Описание
Ако секундите са по-малко от 10, **изваждаме** водеща нула преди тях.

Може би трябва да бъде извеждаме.
## Текущ текст
изваждаме

## Текст след поправката
извеждаме

**Comment by udarensamolet** [comment]
Fixed with [55350b4](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/55350b4879e41460b66b432e2a951323799c3577).
