### ISSUE TITLE
Грешен линк към тестване в Judge на последната задача от Глава 8.1.

### ISSUE THREAD

**Issue by vladislav-todorov** [SoftUni/Programming-Basics-Book-CSharp-BG#238]
## Линк към файла
https://csharp-book.softuni.bg/chapter-08-exam-preparation.html
## Описание
Линкът към тестването в Judge на последната задача от Глава 8.1. е грешен (текстът е наред), затова пращам html код.
## Текущ текст
[a href="Jud11">https://judge.softuni.bg/Contests/Practice/Index/516#11</a]
## Текст след поправката
[a href="https://judge.softuni.bg/Contests/Practice/Index/516#11" target="_blank">https://judge.softuni.bg/Contests/Practice/Index/516#11</a]

**Comment by protegeto** [comment]
<a href="https://judge.softuni.bg/Contests/Practice/Index/516#11" target="_blank">https://judge.softuni.bg/Contests/Practice/Index/516#11</a>

**Comment by vladislav-todorov** [comment]
Използвам съм "[" вместо "<" в началото на текста и "]" вместо ">" в края на текста, защото в противен случай не се вижда проблема в кода!

**Comment by udarensamolet** [comment]
Fixed with [d2acb56](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/d2acb5638ca216816bf958c5cc21ecc9857903e6).
