### ISSUE TITLE
Грешка в "Насоки и подсказки" на последната задача от Глава 8.1.

### ISSUE THREAD

**Issue by vladislav-todorov** [SoftUni/Programming-Basics-Book-CSharp-BG#239]
## Линк към файла
https://csharp-book.softuni.bg/chapter-08-exam-preparation.html
## Описание
Има лексикална грешка в "Насоки и подсказки" на последната задача от Глава 8.1.:
вместо думата "лице" е използвана думата "обем".
## Текущ текст
Ще създадем един брояч и една променлива, която ще използваме за пресмятането на <b>обема</b> на четириъгълника.
## Текст след поправката
Ще създадем един брояч и една променлива, която ще използваме за пресмятането на <b>лицето</b> на четириъгълника.
## Допълнителна поправка
Също така трябва да се смени и името на променливата в "https://csharp-book.softuni.bg/assets/chapter-8-1-images/12.Generating-rectangles-01.png" и "https://csharp-book.softuni.bg/assets/chapter-8-1-images/12.Generating-rectangles-03.png" от <b>volume</b> на <b>area</b>

**Comment by vncpetrov** [comment]
Fixed.
