### ISSUE TITLE
C# book judge contest

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#24]
Направил съм judge contest категория за C# книгата: https://judge.softuni.bg/Contests/#!/List/ByCategory/96/CSharp-Book

Идеята е там да направим по едно състезание за всяка глава от книгата и да вкараме всяка една от задачите от съответната глава.

**Comment by vallenti** [comment]
Създадени са състезанията. Засега нямата задачи качени в тях.

**Comment by udarensamolet** [comment]
всички тестове са качени в judge
