### ISSUE TITLE
Неточно условие към последната задача от Глава 8.1.

### ISSUE THREAD

**Issue by vladislav-todorov** [SoftUni/Programming-Basics-Book-CSharp-BG#240]
## Линк към файла
https://csharp-book.softuni.bg/chapter-08-exam-preparation.html
## Описание
В условието пише, че се търси изход във формат: 
<code>(left, top) (bottom, right) -> area</code>.
В "Насоки и подсказки" пише, че:
<code>С променливите i и k ще следим координатите по хоризонталата, а с j и l - по вертикалата.</code>
<code>...</code>
<code>Console.WriteLine("({0}, {1}) ({2}, {3}) -> {4}", i, j, k, l, area<sup>това е report-нато в друго issue</sup>);</code>
Следователно, за да не трябва да се сменя целия код на решението, а също така и всички тестове, трябва да се размени мястото на bottom и right в примера за форматиране на резултатите в условието.
## Текущ текст
Генерираните правоъгълници да се отпечатат в следния формат:
<code>(left, top) <b>(bottom, right)</b> -> area</code>
## Текст след поправката
Генерираните правоъгълници да се отпечатат в следния формат:
<code>(left, top) <b>(right, bottom)</b> -> area</code>
## Допълнително пояснение към условието, което е редно да бъде добавено
Никъде в условието на задачата не е пояснена посоката на осите на координатната система. Понеже това е курс по "Основи на програмирането с C#" и е подходяща за напълно начинаещи в програмирането хора, то тяхната първоначална представа за координатна система е свързана с часовете по математика, а именно Декартова координатна система с ос X насочена <code>надясно</code> и ос Y насочена <code>нагоре</code>. Докато в задачата се използва координатна система, която ползва посоките на екранната такава, а именно ос Х нараства <code>надясно</code> и ос Y нараства <code>надолу</code>. Затова смятам, че е коректно това да бъде изрично упоменато в условието на задачата. Все пак поради широкоразпространената представа за правоъгълна координатна система, това:
<code>-n ≤ top < bottom ≤ n</code>,
може да бъде прието като грешка в условието и да бъде пренебрегнато, като впоследствие би довело до излишна загуба на време от страна на решаващия задачата.

**Comment by udarensamolet** [comment]
Fixed with [239dd37](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-08-exam-preparation.md).
