### ISSUE TITLE
Глава 10 (методи): грешка, докладвана в GitBook

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#241]
Глава 10 (методи)
--------------------

Да се провери тази грешка: https://www.gitbook.com/book/software-university-foundation/programming-basics-csharp-bg/discussions/6

Ако е грешка, да се поправи и в Java книгата.

**Comment by udarensamolet** [comment]
Fixed with [a02d6f3](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/a02d6f3d1393cda0b2220caa8e800b362e643510).

@nakov Моля да затвориш дискусията в GitBook.
