### ISSUE TITLE
Липсваща задача в Judge в глава 7.1 (По-сложни цикли)

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#242]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-07-complex-loops.md#Вложени-цикли-и-операторът-break

## Описание

Задачата за комбинации с два вложени цикъла липсва в judge. Имаме задача, имаме и решение, но нямаме judge. Трябва да има. Като се поправи, трябва да се преномерират и линковете към другите задачи в judge.

**Comment by udarensamolet** [comment]
Done.
