### ISSUE TITLE
Два варианта на задача в judge в глава 7.1 (за try-catch примера)

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#243]
## Линк към файла

Това са две различни варианта на една задача, но са линкнати към едни и същи тестове в judge:

https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-07-complex-loops.md#Пример-оператор-break-в-безкраен-цикъл

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-07-complex-loops.md#Пример-Справяне-с-грешни-числа-чрез-try-catch

## Описание

Имаме една и съща задача в 2 варианта:
 - без грешни числа (без да трябва `try-catch`)
 - с грешни числа (с нужда от `try-catch`)

Да се направят 2 отделни задачи в judge, защото в първата задача трябва да се подават само валидни числа, а във втората задача трябва да се подават валидни числа + невалидни числа. Тестовете не трябва да са еднакви.

## Fix

За монента добавих този бърз fix. Може и с него да останем:

> Внимание, **някои от тестовете е нормално да не минат**, защото съдържат грешни числа (текст вместо число). С тях ще се справим по-късно, когато се запознаем с **`try-catch`** конструкцията.

**Comment by udarensamolet** [comment]
Done.
