### ISSUE TITLE
Глава 7 (По-сложни цикли): има излишни картинки в assets/chapter-7-images

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#244]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/tree/master/assets/chapter-7-images

## Описание

В посочената папка има еднакви повтарящи се картинки. Вероятно са останали при промяна на имената на картинките (преномериране). **Да се изтрият излишните файлове**.

**Comment by udarensamolet** [comment]
Fixed with [1e5d485](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/1e5d485b34112bcbd4e9c03e8d5a089a7d407423).
