### ISSUE TITLE
Тестове за задача "Пресмятане с дати: 1000 дни на Земята" от Тема 2

### ISSUE THREAD

**Issue by anton5rov** [SoftUni/Programming-Basics-Book-CSharp-BG#245]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-02-simple-calculations.md#Задача-пресмятане-с-дати---1000-дни-на-Земята
## Описание
В упражненията към лекцията 2. Simple-Calculations-Exercises.docx е даден линк към джъдж https://judge.softuni.bg/Contests/Practice/Index/151#12, който приема за правилно да се добавят 999 дни, а не 1000. Не съм съгласен с тази логика и не мога да я обясня на курсистите. В книгата за съответната задача пък е даден линк  https://judge.softuni.bg/Contests/Practice/Index/504#12, който приема решения с добавяне на 1000 дни, а не на 999. Да оправим тестовете за джъдж към задачата от курса, или да сменим линка в текстовия файл, да сочи към варианта от книгата?

**Comment by udarensamolet** [comment]
@nakov Нужно ни е мнението ти.

**Comment by nakov** [comment]
Ами да, давайте с 1000 дни. Тое въпрос на формулировка на задачата + обясненията към нея _ най-вече примерите. Оправете го с 1000.
