### ISSUE TITLE
Глава 8.1, задача "Генериране на правоъгълници": глупави имена на променливи

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#246]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-08-exam-preparation.md#Насоки-и-подсказки-11

## Описание

Имената на променливите `i`, `j`, `k`, `l` не казват нищо по въпроса какво има в тези променливи. Просто някакви буквички. Правилните имена са дадено още в условието на задачата:
- `top`
- `bottom`
- `left`
- `right`

**Comment by vncpetrov** [comment]
Fixed.
