### ISSUE TITLE
Некачествен код в Глава 8.1, задача "Генериране на правоъгълници"

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#247]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-08-exam-preparation.md#Насоки-и-подсказки-11

## Описание

Променливата `area` е декларирана твърде рано без да е нужно. Може да се декларира много по-късно -> в най-вътрешния цикъл. Това ще направи кода по-лесен за четене, защото ще намали **variable span** и **variable scope**.

**Comment by vncpetrov** [comment]
Fixed.
