### ISSUE TITLE
Лошо име на променлива в Глава 8.1, задача "Поредица от нарастващи елементи"

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#248]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-08-exam-preparation.md#Насоки-и-подсказки-7

## Описание

Променливата `countTempLongest` е с кофти име. Да се именува `countCurrentLongest`.

**Comment by vncpetrov** [comment]
Fixed.
