### ISSUE TITLE
Объркана задача: "Известия" в глава "10. Методи"

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#249]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-10-methods.md#Задача-известия

## Описание

**Описанието на задачата "Известия" е доста объркано** и не съответства а примерния вход и изход. Аз лично няколко пъти го четох и не го разбрах, примерите не можах да ги разгадая и като цяло ми се стори странно изискваното поведение.

## Коментари

Предлагам няколко промени:
 - От входа да се четет `n` съобщения. Всяко съобщения започва с `messageType`: `success`, `warning` или `error`.
 - При `success` да се четат `operation` + `message`.
 - При `warning` да се чете само `message`.
 - При `error` да се чете `operation` + `message` + `errorCode`.
 - В изхода да се сложи по един празен ред след всяка команда.
 - В изхода след заглавния ред за всяка съобщение да се отпечатат толкова силвола `=`, колкото е дълъг съответният заглавен ред (вж. примерния изход).

Примерен вход:
```
4
error
credit card purchase
Invalid customer address
500
warning
Email not confirmed
success
user registration
User registered successfully
warning
Customer has not email assigned
```

Примерен изход:
```
Error: Failed to execute credit card purchase.
==============================================
Reason: Invalid customer address.
Error code: 500.

Warning: Email not confirmed.
=============================

Successfully executed user registration.
========================================
User registered successfully.

Warning: Customer has not email assigned.
=========================================

```

Съответно трябва да се напишат няколко метода:

```csharp
static void ShowSuccessMessage(string operation, string message) { ... }

static void ShowWarningMessage(string message) { ... }

static void ShowErrorMessage(string operation, string message, int errorCode) { ... }

static void ReadAndProcessMessage()
{
    string messageType = Console.ReadLine();
    switch (messageType) 
    {
        // TODO: check for "success", "warning" and "error"
    }
}
```

Накрая главният метод ще вика останалите методи:

```csharp
static void Main()
{
    int n = int.Parse(Console.ReadLine());
    for (var i=0; i<n; i++)
        ReadAndProcessMessage();
}
```

Да се направят и нови тестове в Judge: https://judge.softuni.bg/Contests/Practice/Index/594#12

**Comment by vncpetrov** [comment]
Промених условието на задачата. Промених и тестовете в Judge. Това е кодът, който използвах: [pastebin.com/m52LshuS](https://pastebin.com/m52LshuS)
Единствения проблем е със символа =, който не излиза добре в книгата:
![image](https://user-images.githubusercontent.com/20843160/32200167-eb0c94a8-bdd8-11e7-8fda-422e93c8e190.png)

Така ли да го оставям или да го направя визуално да изглежда добре?

**Comment by nakov** [comment]
Предлагам да се ползва Monospaced шрифт в изхода: `<code>....</code>`

**Comment by nakov** [comment]
Мисля, че се получи идеално:

![image](https://user-images.githubusercontent.com/1689586/32213632-aaf85284-be24-11e7-9f5b-8e1d266e587c.png)

Огледай за грешки, както и в Judge и ако няма, същото трябва да се пренесе в Java книгата...

**Comment by nakov** [comment]
Задачата е прегледана и е ОК. Затварям дискусията по нея.
