### ISSUE TITLE
Използване на inline html за по-удобни таблици

### ISSUE THREAD

**Issue by tatarski** [SoftUni/Programming-Basics-Book-CSharp-BG#25]
Може ли да се създаде проблем ако използваме inline html за да правим вход/изход?

**Comment by tonyozhelev** [comment]
Принципно видях, че другите така правят така и тръгнах и аз така. Поразчетох се обаче и не можах да намеря начин да се ползва css в md. Примерно за да направим фон на най-горния ред от таблицата. Друг случай .в който ми направи проблем е, когато в едното ми условие се наложи да ползвам таблица, за да може да е по-красиво (от ляво текст и от дясно картинка), но не можах да намеря начин да и махна border-a.

**Comment by tatarski** [comment]
Аз също тръгнах с table. Ако искаш виж глава 6 - рисуване в конзолата - задачи. Там съм сложил картинка от едната страна на таблицата. Надявам се да ти помогне

**Comment by tonyozhelev** [comment]
Да, това ясно, на мен проблема ми е, че не мога да ги кустомизирам повече. До колкото разбрах няма как да се включи css в md, нито пък md стандартните таблици позволяват повече кустомизация.

**Comment by tatarski** [comment]
Не можеш ли със \<table style="**css styling goes here**"> ?

**Comment by tonyozhelev** [comment]
и така пробвах, пак не става

**Comment by hristochr** [comment]
Две неща да добавя:

1. Аз например ползвам инлайн HTML за картинките. Друг вариант не видях до момента.
2. Тука май има инфо за CSS:>[http://markedstyle.com](http://markedstyle.com)

**Comment by tatarski** [comment]
Има начин за слагане на картинки само с md, но той е неприятен.

**Comment by nakov** [comment]
Принципно тествахме inline CSS и работи, примерно нещо такова:
```
<div style="display:inline-block; border: 1px solid blue">left</div>
<div style="display:inline-block; border: 1px solid green">right</div>
```

Това нещо в GitBook ще се рендира правилно и ще направи нещо като таблица с 2 колонки. В GitHub MarkDown reader, обаче, ще изглежда счупено. В крайна сметка в GitBook като HTML и като PDF се рендира коректно. Това е важното.
