### ISSUE TITLE
Повторения (цикли)

### ISSUE THREAD

**Issue by Djarisimo** [SoftUni/Programming-Basics-Book-CSharp-BG#250]
https://csharp-book.softuni.bg/chapter-05-loops.html
## Описание
Има грешка в примера "всички латински букви" когато е с int излизат числа, а не букви и затова го оправих с var, за да изпише азбуката.
## Текущ текст
Console.WriteLine("Latin alphabet:");
            for (int letter = 'a'; letter <= 'z'; letter++)
            {
                Console.WriteLine(" " + letter);
            }
            Console.WriteLine();
## Текст след поправката
Console.WriteLine("Latin alphabet:");
            for (var letter = 'a'; letter <= 'z'; letter++)
            {
                Console.WriteLine(" " + letter);
            }
            Console.WriteLine();

**Comment by nakov** [comment]
Потвърждавам: сгрешено е. Трябва да е `var` или `char`.

**Comment by nakov** [comment]
fixed
