### ISSUE TITLE
 Грешка в единия изход на задача "поредица от нарастващи елементи", Глава 8.1.

### ISSUE THREAD

**Issue by georgiangelovvv** [SoftUni/Programming-Basics-Book-CSharp-BG#251]
## Линк към файла
https://csharp-book.softuni.bg/chapter-08-exam-preparation.html
## Описание
При четвъртия примерен вход, изходът трябва да е **4**, вместо **2**.

## Текущ текст
![old](https://user-images.githubusercontent.com/35844513/35449180-f828cb6c-02c4-11e8-8b62-aaa245d4a424.PNG)

## Текст след поправката
![new](https://user-images.githubusercontent.com/35844513/35449196-04a66304-02c5-11e8-869e-5529b92176ed.PNG)

**Comment by nakov** [comment]
Благодаря. Грешката е много стара, имаше я и в 6-те книги, и в Markdown, и в DOCX и в PDF и отне доста време да се оправи навсякъде, но успях. Затварям този въпрос.
