### ISSUE TITLE
Грешки в задачите на Глава 9.1. Задачи за шампиони – част I

### ISSUE THREAD

**Issue by NikolayIT** [SoftUni/Programming-Basics-Book-CSharp-BG#252]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-09-problems-for-champions.md

## Описание
Има значителни пропуски и грешки в условията, тестовете и отчасти и на решенията на задачите в главата. Можете да видите моите поправки в главата за JS, откъдето да пренесете поправките върху задачите: https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/chapter-09-problems-for-champions/chapter-09-problems-for-champions.md

**Comment by nakov** [comment]
fixed
