### ISSUE TITLE
Тестове за всички задачи от всички глави в книгата

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#26]
Да се качат тестовете за всички задачи в Judge системата.

Тестовете могат да се изтеглят от тук: https://github.com/Software-University/Tests?files=1

Да се адаптират тестовете, ако е необходимо.

Да се налеят тестовете в категорията на книгата: https://judge.softuni.bg/Contests/#!/List/ByCategory/96/CSharp-Book

**Comment by nakov** [comment]
За момента @vallenti има достъп да качва задачи и тестове. Може на него да му ги давате.

**Comment by Teodor92** [comment]
@vallenti
Тестовете за Chapter 9, Part 2 - https://www.dropbox.com/s/l3b4y915byaka43/chapter-9-part-2-tests.rar?dl=0

**Comment by erogleva** [comment]
@vallenti Тестовете за Chapter 2, Part 2 - https://drive.google.com/open?id=0BzGHMIfKmKv7YzVZRHZwZGRCRnM

**Comment by udarensamolet** [comment]
@vallenti Тестове за Chapter 3, Part 2 Simple conditions - Exam problems: https://www.dropbox.com/s/2fhbq98dy2z6qh4/3.2.%20Simple%20conditional%20statements%20-%20Exam%20problems.rar?dl=0

**Comment by tatarski** [comment]
@vallenti Тестове за Chapter 6, Part 2 - Drawing in the console part 2
https://www.dropbox.com/s/xmv56dxt2saczxh/6.%20Drawing%20in%20the%20console%20part%202%20tests.rar?dl=0
Липсват тестовете за задача "Знак Стоп"

**Comment by bankin** [comment]
@vallenti Тестове за Глава 9
[Chapter9-Tests.zip](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/files/888609/Chapter9-Tests.zip)

@nakov След като тестовете се налеят и задачите се създадат по глави, може би е хубаво да минем и да си ъпдейтнем линковете към judge да сочат към тази категория? Може би редакторите на главите да го направят? Някакъв друг вариант?

**Comment by rextor92** [comment]
@vallenti Тестове за: Глава 7. По-сложни цикли - изпитни задачи.
https://1drv.ms/u/s!AvhXFTVxxpbhsnKjdYpc_T_A5DJD

Липсват тестове за задача "Комбинации от букви". Задачата от изпита е на [този адрес](https://judge.softuni.bg/Contests/Practice/Index/368#5)

**Comment by Antoveravip** [comment]
**@vallenti**  - [Тестове](https://github.com/Antoveravip/Software-University/tree/master/ExamTasks/Tests) за Глава 4.2. По-сложни проверки - изпитни задачи.
