### ISSUE TITLE
Тестване на програмите описани в книгата

### ISSUE THREAD

**Issue by tonyozhelev** [SoftUni/Programming-Basics-Book-CSharp-BG#27]
Предлагам всеки да си направи едно репозитори със решените задачи, за да не си играят редакторите да пишат кода наново, ами директно да си го тестват (добре е да поглеждат и дали съвпада с този в книгата). Аз направих такова в собствения си профил и го споделих с редактора си ( https://github.com/tonyozhelev/programming-basics-problems/tree/master ), но ако искате, може да направим някъде едно общо и всеки да слага там кодовете, които е написал.

**Comment by Teodor92** [comment]
Лично съм за общо репо, което да се хоства в SoftUni профила.

**Comment by Teodor92** [comment]
Но най-добре е @nakov да каже, как да процедираме.

**Comment by Antoveravip** [comment]
Докато се избере общо репо: ето [моите решения](https://github.com/Antoveravip/Software-University/tree/master/ExamTasks/MoreComplexChecks) към глава 4.2. По-сложни проверки - изпитни задачи.

**Comment by erogleva** [comment]
Eто и от мен https://github.com/erogleva/CSharp-Book_Solutions за Simple Calculations - Exam problems, редактор е @sevan3x доколкото виждам :)

**Comment by sevan3x** [comment]
благодаря, събота и неделя ще започна работа по проверката :)

2017-04-05 18:40 GMT+03:00 Elena Rogleva <notifications@github.com>:

**Comment by sevan3x** [comment]
@erogleva благодаря, събота и неделя ще започна работа по проверката :)

**Comment by vncpetrov** [comment]
Completed.
