### ISSUE TITLE
Вкарване на видео

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#3]
Да се проучи как да се вкара видео за всяка глава.

**Comment by mchaov** [comment]
Стига да го има в YouTube
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#videos

**Comment by nakov** [comment]
Можем да ползваме видеа за повечето глави от този курс (водени от Наков): https://softuni.bg/trainings/1297/programming-basics-january-2016.

**Comment by nakov** [comment]
Измислихме [кадърен начин да вмъкваме YouTube видео](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/wiki/%D0%9D%D0%B0%D1%81%D0%BE%D0%BA%D0%B8-%D0%BA%D1%8A%D0%BC-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D1%82%D0%B5#%D0%92%D0%BC%D1%8A%D0%BA%D0%B2%D0%B0%D0%BD%D0%B5-%D0%BD%D0%B0-youtube-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE).

Кодът вмъква responsive YouTube video player ако реднираме към HTML или текст + link, ако реднираме към PDF или четем текста с GitHub markdown reader.
