### ISSUE TITLE
Изходни данни на по сложни задачи за рисуване в конзолата

### ISSUE THREAD

**Issue by tatarski** [SoftUni/Programming-Basics-Book-CSharp-BG#31]
Ще може ли да сложим изходните данни на по сложните задачи за рисуване в конзолата като изображения ?

**Comment by Teodor92** [comment]
Ако става въпрос за примерите от 0-вите тестове не мисля че е добра идея т.к. означава, че който пише задача и иска да я тества ще трябва да преписва от картинката, вместо да я copy-paste-не. Then again, 0-вите тестове се показват и в judge-a, така че може да не е чак такъв голям проблем.

**Comment by tatarski** [comment]
Мисля, че с <pre></pre> информацията става четима и се escape-ват специалните за markdown символи.

**Comment by ChrisPam** [comment]
Съгласен съм с @tatarski 👍
