### ISSUE TITLE
Magic Dates Memory Limit Issue

### ISSUE THREAD

**Issue by bankin** [SoftUni/Programming-Basics-Book-CSharp-BG#32]
Здравейте, 

За главата "Задачи за шампиони" съм подбрал Magic Dates задачата (https://judge.softuni.bg/Contests/Practice/Index/6#3). 

Проблемът ми е, че на "най-големия" тесткейс решението ми гърми с Memory Limit. Проблемът е в смятането на "тежестта" + toString извикването за дадена дата(по мое мнение). Пробвах различни варианти (включващи само знанията, които курсистите би трябвало да имат от курса, т.е. без масиви или някакви други неща) и освен да хардкодна самата сметка (тъй като тя ще бъде еднаква всеки път) нищо друго не даде 100 точки, а на мен не ми харесва да дам такова решение и по-скоро, ако не успея да "смъкна паметта" ще сменя задачата. 
Приемам предложения какво мога да подобря, за да мине задачата.

Пействам направо кода, защото не мога да кача `.cs` файл.
Закоментираните неща съм ги пробвал и не работя

```
int startYear = int.Parse(Console.ReadLine());
int endYear = int.Parse(Console.ReadLine());
int magicWeight = int.Parse(Console.ReadLine());

bool printed = false;

DateTime currentDate = new DateTime(startYear, 1, 1);

while (currentDate.Year <= endYear)
{
    int dateWeight = 0;
    //string dateString = "" +
    //    currentDate.Day +
    //    currentDate.Month + 
    //    currentDate.Year;
    string dateString = currentDate.ToString("dMyyyy");
    int dateLength = dateString.Length;
    //int dateNum = int.Parse(dateString);

    //int d1 = currentDate.Day / 10;
    //int d2 = currentDate.Day % 10;
    //int d3 = currentDate.Month / 10;
    //int d4 = currentDate.Month % 10;
    //int d5 = (currentDate.Year / 1000) % 10;
    //int d6 = (currentDate.Year / 100) % 10;
    //int d7 = (currentDate.Year / 10) % 10;
    //int d8 = (currentDate.Year / 1) % 10;
    
    // This works.
    //dateWeight = d1 * (d2 + d3 + d4 + d5 + d6 + d7 + d8) +
    //             d2 * (d3 + d4 + d5 + d6 + d7 + d8) +
    //             d3 * (d4 + d5 + d6 + d7 + d8) +
    //             d4 * (d5 + d6 + d7 + d8) +
    //             d5 * (d6 + d7 + d8) +
    //             d6 * (d7 + d8) +
    //             d7 * d8;

    for (int i = 0; i < dateLength - 1; i++)
    {
        //int multiplier = (dateNum / ((int)Math.Pow(10, dateLength - i - 1))) % 10;
        for (int j = i + 1; j < dateLength; j++)
        {
            //int digit = (dateNum / ((int)Math.Pow(10, dateLength - j - 1))) % 10;
            //dateWeight += multiplier * digit;

            dateWeight += (dateString[i] - '0') * (dateString[j] - '0');
        }
    }

    if (dateWeight == magicWeight)
    {
        Console.WriteLine(currentDate.ToString("dd-MM-yyyy"));
        printed = true;
    }

    currentDate = currentDate.AddDays(1);
}

if (!printed)
{
    Console.WriteLine("No");
}
```

**Comment by Teodor92** [comment]
Хардкодването на пресмятането не е лош варинат - имах същия проблем с една от моите задачи и хардкодването се оказа единственото нормално решение.
Алтернативно може да се вдигне memory constraint-a на задачата.

**Comment by ChrisPam** [comment]
Аз вдигнах memory constraint-а. Ако сте намерили алтернативно решение, което минава 100/100 при малкия memory constraint и е разбираемо. Може да пишете да го намаля :)

**Comment by bankin** [comment]
Вече всички решения минават тей използват 17-18м пък ограничението беше 16. Но в книгата съм записал решение, което минава и на първоначалния лимит. Може би ще добавя един параграф да тестват алтернативни подходи. 

Благодря все пак! :)
