### ISSUE TITLE
Редакция на глава

### ISSUE THREAD

**Issue by ChrisPam** [SoftUni/Programming-Basics-Book-CSharp-BG#36]
Понеже целим книгата да я уеднаквим, можем тук да си пишем някакви общи концепции, тъй като аз не видях нещо определено само за редакторите. Какво ще кажете?

Пример:

След всяка задача в края на задачата да изписваме точно този текст, защото видях, че някои са в началото
### Задача: Числата от N до 1 в обратен ред
...
...
...
Тествайте вашето решение тук: https://judge.softuni.bg/Contests/Practice/Index/514#1

### Задача: Числата от 1 до 2^n с for-цикъл

**Comment by VaskoViktorov** [comment]
Харесва ми идеята. Ето и моето предложение:

За примерните задачи и задачите за упражнение, в заглавията да се ползва Heading 3 и винаги да се изписва по следния начин:  Задача:<наименование> или Пример:<наименование>.

Пример:

###Задача: Числата от N до 1 в обратен ред
###Пример: Числата от N до 1 в обратен ред

**Comment by stefkavasileva** [comment]
Напълно съм съгласна с  вас, затова предлагам таблиците също да бъдат в един и същи формат. В едни глави са HTML, а в други Markdown. Разглеждах книгата през телефон и по-добрият вариант според мен е вторият.

**Comment by ChrisPam** [comment]
Също така видях, че всеки човек различно замъглява, предлагам да се минат всичките скрийншоти по един и същ начин, аз мога да го поема. Какво мислите вие?

**Comment by udarensamolet** [comment]
@ChrisPam go go blurring ranger
иначе за таблиците и аз мисля, че е по-добре markdown варианта. също така, както наков беше писал - добре да се прегледат как изглеждат на телефон и таблет и тези таблици, които са с повече колонки, да се разделят на няколко отделни таблички

**Comment by ChrisPam** [comment]
Добре направих файла :) Включих и вашите предложения
