### ISSUE TITLE
Глава 2. Прости пресмятания с числа - изпитни задачи

### ISSUE THREAD

**Issue by ChrisPam** [SoftUni/Programming-Basics-Book-CSharp-BG#37]
Искам само да отбележа, че при Mobile/tablet таблиците се чупят. Предложението ми към автора и редактора е да се премахне последната колона "Обяснение" и да се опише, ако е нужно под таблицата. А самата таблица да държи в себе си само Вход/Изход :)

**Comment by erogleva** [comment]
Окей, благодаря за забележката, ще го оправя :)

**Comment by ChrisPam** [comment]
:)
