### ISSUE TITLE
Глава 5.2 - Липсваща здача в Judge

### ISSUE THREAD

**Issue by KaPrimov** [SoftUni/Programming-Basics-Book-CSharp-BG#38]
Здравейте, 

Последната задача ("Логистика") в глава 5.2. Loops - Exam Problems няма секция в контеста в Judge. Ето линк към нея от предишен изпит: https://judge.softuni.bg/Contests/Practice/Index/359#3.

Благодаря предварително!

**Comment by ChrisPam** [comment]
Чакам да получа тестовете на задачата и ще я кача :)
