### ISSUE TITLE
Умен начин за convert от MS Word към Markdown

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#4]
Да се потърси умен начин за convert от MS Word към Markdown.

**Comment by Teodor92** [comment]
http://www.tablesgenerator.com/markdown_tables

**Comment by mchaov** [comment]
https://gist.github.com/vzvenyach/7278543

https://stackedit.io/
https://word-to-markdown.herokuapp.com/
https://jbt.github.io/markdown-editor/

**Comment by ChrisPam** [comment]
Плъгин за read-ване на MD. След като се отвори файла с word може да се edit-ва и след това автоматично си написва MD. http://www.writage.com . Работи доста добре

**Comment by Masovski** [comment]
[Pandoc - Demos](http://pandoc.org/demos.html) (command line tool) може да конвертира **docx към Markdown** (пример **№35**).

Доста мощен инструмент. Писан е на Haskell и е с [отворен код](https://github.com/jgm/pandoc).
Има [изключително подробен manual](http://pandoc.org/MANUAL.html).
