### ISSUE TITLE
Излишна задача в Judge contest-а за глава 4. По-сложни проверки

### ISSUE THREAD

**Issue by KaPrimov** [SoftUni/Programming-Basics-Book-CSharp-BG#41]
Здравейте, 
В contests-a за четвърта глава - Complex conditions има задача. която я няма като пример в глава. Става въпрос за 5-та задача Invalid Numbers (https://judge.softuni.bg/Contests/Practice/Index/508#4):

![image](https://cloud.githubusercontent.com/assets/19434127/25335080/23cbaaa0-28fa-11e7-9f5e-f9877a750349.png)

Предполагам, че е авторско решение да я няма задачата, така че можете ли да я махнете от contest-a, за да не се объркват хората?

**Comment by udarensamolet** [comment]
@KaPrimov аз я виждам в книгата, сигурен ли си, че за тази става въпрос?

![image](https://cloud.githubusercontent.com/assets/5997265/25335305/27701cda-28fb-11e7-9237-e6de10cd2f25.png)

**Comment by KaPrimov** [comment]
Извинявай много, моя грешка и нямам идея и какво съм гледал.
