### ISSUE TITLE
Markdown към Word

### ISSUE THREAD

**Issue by udarensamolet** [SoftUni/Programming-Basics-Book-CSharp-BG#42]
Да се намери начин да се пренесе в Word

**Comment by Teodor92** [comment]
[Pandoc](http://pandoc.org/) е най-доброто free решение. Ползвал съм го на Linux, но 100% има съпорт и за Windows.

[http://bob.yexley.net/generate-a-word-document-from-markdown-on-os-x/](http://bob.yexley.net/generate-a-word-document-from-markdown-on-os-x/)

**Comment by nakov** [comment]
Имам следното решение:
1. Съединяват се всички глави в един **общ HTML файл**: може да стане client-side JS код с jQuery + AJAX, който тегли главите една по една и ги налива в HTML документа една след друга.
 - Написах примерен скрипт: https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/resources/Scripts/merge-all-book-chapters.js
2. HTML файлът се обръща в **DOCX** или **RTF** през **Calibre** (https://calibre-ebook.com)
 - Calibre се справя доста добре за DOCX. Форматира правилно и таблиците и текста и кода, без да ги чупи. Единственият дефект е, че заглавията не стават коректно в Heading 1, Heading 2, Heading 3, ... Изглежда като бъг. Но като цяло качеството е добра, доста добро.
3. Върху **DOCX файла** се правят **корекции**. Файлът е много далеч от перфектен и има нижда от доста обработка.
 - Може групово да се селектират различните елементи по техния стил, примерно всички параграфи, всички думи с шрифт Consolas и подобни и да се променят.
 - Картинките трябва да се оправят.
 - Таблиците са добре като цяло.
 - Останалият текст, списъци, сорс код и подобни също са ОК като цяло.

**Comment by udarensamolet** [comment]
Решение се намери: Светлин Наков написа софтуер, който прехвърля книгата от Markdown към HTML и после към MS Word с високо качество.
[Разработената технология за прехвърляне от Markdown към MS Word](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/tree/master/resources/Prepress-Scripts)
