### ISSUE TITLE
Small mistake - не е центрирано правилно

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#46]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-1-first-steps-in-programming.md

Примерен вход и изход

a	b	area
2	7	14
7	8	56
12	5	60

Числата 14 56 60 не са центриране в средата на клетката.

**Comment by Teodor92** [comment]
Fixed with 2088394f4c48a298cfccb532a4a9c94cb4e82bbe
