### ISSUE TITLE
Граматична грешка

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#47]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-1-first-steps-in-programming.md

**Като браузърът ни играе главната роля** по обработката на зададените в програмата команди.
1 Какъв е смисъла на паразитната дума КАТО в това изречение?
2 Браузърът ни - какъв е смисъла на частицата **ни** в изречението?
Браузърът играе главната роля по обработката на зададените в програмата команди.

**Comment by udarensamolet** [comment]
Fixed with [d7a92dc](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/d7a92dc3e378685d4cfbad628963ed50f891cc12)
