### ISSUE TITLE
Грешка в таблицата

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#48]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops.md

Таблицата няма редове със бяло и сиво както е на други места в книгата няма консистенция.

a	 b	НОД
24     16        8
67     18        1
12     24      12
15      9         3
10     10      10 
100	 88	    4

**Comment by Teodor92** [comment]
Това се дължи на факта, че всички стойности се намират на един ред. Може би наистина е хубаво стойностите да се разделят на отделни редове.

**Comment by udarensamolet** [comment]
Fixed with [81ac6ed](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/81ac6ed5c9eb1073dfb3bc0a115902eb497d4ae8)
