### ISSUE TITLE
Пропусната буква

### ISSUE THREAD

**Issue by kaykayehnn** [SoftUni/Programming-Basics-Book-CSharp-BG#49]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions.md
## Описание
Нулев тест 2(-1, 1)
## Текущ текст
bcdea cebda ... eeea
## Текст след поправката
bcdea cebda ... eeea**d**

**Comment by udarensamolet** [comment]
Fixed with [81ac6ed ](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/b62515e741694278335a888530af0c3d11c2404e)
