### ISSUE TITLE
Излишни кавички

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#50]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-7-complex-loops-exam-problems.md

всички "магически" числа

магическите числа

Първият път е със двоини кавички после без кавички.Няма консистенция в текста.

**Comment by Teodor92** [comment]
Fixed with: a2e29a1a1c77a0edf3eabba51a9b0bd593dee0d1
