### ISSUE TITLE
Неяснота в текста

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#51]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-2-simple-calculations.md

Преди:   Можете да ползвате следния код за ориентир:

Може да се напише по ясно това изречение.Какво е това ориентир много сложна дума??

След:     Можете да ползвате следния примерен код:

**Comment by Teodor92** [comment]
Fixed with: 6f370cda73f5bd2ada3030bf50bd694cd0b1c487
