### ISSUE TITLE
Грешка в условие/джъдж

### ISSUE THREAD

**Issue by kaykayehnn** [SoftUni/Programming-Basics-Book-CSharp-BG#52]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md
## Описание
Задача бикове и крави, в джъдж се подават тестове със само два реда вход, а в условието на задачата се искат три.
https://judge.softuni.bg/Contests/Practice/Index/519#2

**Comment by Teodor92** [comment]
Линк към коректните тестове: https://www.dropbox.com/s/86do4gbzn0t2s5m/BullsAndCowsCorrect-Tests.rar?dl=0

**Comment by udarensamolet** [comment]
Тестовете са коригирани
