### ISSUE TITLE
Грешна буква

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#53]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-2-simple-calculations-exam-problems.md

Както и в предходните задачи, можем да разделим решението на три подзадачи:

Прочитане на входните данни.
Извършване на изчисленията.
**и**звеждане на изход на конзолата.

Защо последното е със малка буква??

**Comment by Teodor92** [comment]
Fixed with: 38d732b15f79b58b3e84c8b561432627d59a9074
