### ISSUE TITLE
Грешка в условието на задачата

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#54]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-2-simple-calculations-exam-problems.md

Резултатът да се форматира до втория знак след запетаята.
Изход
74.61

Какво означава **след запетаята** като разделителя е точка??

**Comment by Teodor92** [comment]
Това е доста добра забележка и довежда до други въпрос - Какво е използвано за десетичен разделител в книгата - точка или запетая? Има ли консистенция? И какво подава, по подразбиране, 
 онлайн системата([https://judge.softuni.bg/](https://judge.softuni.bg/))?

@udarensamolet @vncpetrov

**Comment by vncpetrov** [comment]
В Judge системата тестовете са с точка. В книгата също е използвана точка за десетичен разделител, дори мисля, че някъде беше обяснено как се променя десетичния разделител.

**Comment by udarensamolet** [comment]
Fixed with [fb81a1b](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/fb81a1b47557a5ef22ff03b2a839829261b1950c)
