### ISSUE TITLE
Грешка в описанието.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#55]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-2-simple-calculations-exam-problems.md

euro -= commission * euro
euro = euro - (commission * euro)**;**

Защо на първия ред липсва **;** a на ред две има ; на  края??
Липсва консистенция.

**Comment by Teodor92** [comment]
Fixed with: e72a7825bbdb091b26432875e494b510035e92ea
