### ISSUE TITLE
Грешка в името на променлива

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#56]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-2-simple-calculations-exam-problems.md

Лицето на единична плочка изчисляваме като умножим едната ѝ страна по другата W * **H**

От къде идва това **Н** може би е L- дължината на една плочка.

Лицето на единична плочка изчисляваме като умножим едната ѝ страна по другата W * L

**Comment by udarensamolet** [comment]
Fixed with [8d9ff92](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/5f62ade163e68fb88c94d5dfc75e622bce9d0d30)
