### ISSUE TITLE
Грешка в подчертаването

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#57]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-2-simple-calculations-exam-problems.md

Обяснение:

**Обща площ** = 20 * 20 = 400.
Площ на **пейката** = 1 * 2 = 2.
**Площ за покриване** = 400 – 2 = 398.
**Площ на плочки** = 5 * 4 = 20.
**Необходими плочки** = 398 / 20 = 19.9.
**Необходимо време** = 19.9 * 0.2 = 3.98.

 Площ на     не е bold.

**Comment by Teodor92** [comment]
Fixed with 60a956f9caa245701455eea65f417fb5b40ec692
