### ISSUE TITLE
10^28 != 1028

### ISSUE THREAD

**Issue by kaykayehnn** [SoftUni/Programming-Basics-Book-CSharp-BG#58]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md
## Текущ текст
Парите са число с плаваща запетая в интервала: [0 - 7.9 x **1028**].
## Текст след поправката
10^28 или 28 суперскрипт

**Comment by Teodor92** [comment]
Fixed with: 7f662db3318b262b74a7661137955dfb40f8bd58
