### ISSUE TITLE
Липсва точка за край на изречението.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#59]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

 Парите на Лина не могат да бъдат по-малко от 0

Липсва точка за край на изречението.

**Comment by Teodor92** [comment]
Fixed with: af6bc8e288082e827786bb8353e3a3398052059e
