### ISSUE TITLE
Spell checker for BG

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-CSharp-BG#6]
Да се потърси spell checker техника за Markdown.

**Comment by mchaov** [comment]
Spell check-а на браузърите може да се ползва, ако използваме web editor. Има и допълнителни разширения за Хром и Лисицата.

**Comment by Teodor92** [comment]
Плюс почти всеки локален Text Editor/IDE си има plugin-и за Markdown и spell checker.
