### ISSUE TITLE
Излишно сложна дума

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#60]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

Първата част от прочитането е тривиална:

Какво означава тривиално? Много сложна дума.

Прочитаме първия ред от конзолата:

**Comment by vncpetrov** [comment]
http://rechnik.info/%D1%82%D1%80%D0%B8%D0%B2%D0%B8%D0%B0%D0%BB%D0%B5%D0%BD
