### ISSUE TITLE
Български и англииски в една дума

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#61]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

Имайки предвид, че входните данни с командите представляват string-ове

Не ми харесва идеята на български и англииски в една дума.

Имайки предвид, че входните команди са от тип string ,то най-лесния начин да достъпим всеки знак в тях е чрез foreach цикъл.

**Comment by udarensamolet** [comment]
Fixed with [4caedaa](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/97ffff48549c24bfe70792176d19e5ba208dd667)
