### ISSUE TITLE
Липсващи символи(точки)

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#62]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

Имайки предвид, факта, че буквите в азбуката имат ред, можем да използваме следната проверка action >= 'A' && action <= 'Z', за да проверим дали нашият символ се намира в интервала от големи букви
Можем да използваме функцията char.IsUpper(..)

Липсват точки на края на изреченията два броя.

Имайки предвид, факта, че буквите в азбуката имат ред, можем да използваме следната проверка action >= 'A' && action <= 'Z', за да проверим дали нашият символ се намира в интервала от големи букви.
Можем да използваме функцията char.IsUpper(..).

**Comment by Teodor92** [comment]
Fixed with: 1c6b11820bf626c91419ce8bb2545d00cf84832f
