### ISSUE TITLE
Една запетая повече.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#63]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

Смятаме, че читателят не би трябвало да изпита проблем при имплементацията на всички други проверки, защото са много сходни с първата**,** .

Една запетая повече.

**Comment by udarensamolet** [comment]
Fixed with [97ffff4](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/eb73d7a6c5a32d8bd6c57be30c7437d45973b2b4)
