### ISSUE TITLE
Неяснота в условието.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#64]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

Бони е много мощна вещица.

Мощна е колата.По добро прилагателно трябва.

Бони е много силна вещица.

**Comment by udarensamolet** [comment]
Fixed with [d38487e](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/df35ae845689514a10921ad846fada208b29bfab)
