### ISSUE TITLE
Липсващо име на колона

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#65]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

Всички обичаме играта „Бикове и Крави“ (http://en.wikipedia.org/wiki/Bulls_and_cows). При дадено 4-цифрено тайно число и 4-цифрено предполагаемо число, използваме следните правила:

Aко имаме цифра от предполагаемото число, която съвпада с цифра от тайното число и е на същата позиция, имаме бик.
Ако имаме цифра от предполагаемото число, която съвпада с цифра от тайното число, но е на различна позиция, имаме крава.

Предлагам да сложим име на последната колоната Коментар

**Comment by udarensamolet** [comment]
Fixed with [eb73d7a](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/d38487e2049fb428b0000c0f3b76fb91060ed4d9)
