### ISSUE TITLE
Също така неяснота

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#66]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

Също така, оператора по подразбиране е +, за да може още първото срещнато число да бъде събрано с резултата ни.

Също така - нищо не изразява - паразитен израз.

Оператора по подразбиране е +, за да може още първото срещнато число да бъде събрано с резултата ни.

**Comment by udarensamolet** [comment]
Fixed with [606e662](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/606e662088c875336cb4fe2ce19e1c909218e5c6)
