### ISSUE TITLE
Неясно условие

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#67]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md

След като приключим калкулацията на резултата от подизраза ни, модифицираме резултата на целия израз в зависимост от стойността на expressionOperator.

калкулацията,модифицираме пак някаккви чуждици сложни думи.Това подизраза ни също няма голям смисъл .....

След като приключим пресмятането на резултата от подизраза ни,променяме резултата на целия израз в зависимост от стойността на expressionOperator.

**Comment by udarensamolet** [comment]
[Калкулация](http://rechnik.info/%D0%BA%D0%B0%D0%BB%D0%BA%D1%83%D0%BB%D0%B0%D1%86%D0%B8%D1%8F)
[Модификация](http://rechnik.info/%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F)
