### ISSUE TITLE
Kавички

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#71]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions.md

В настоящата глава ще предложим на читателя няколко малко по-трудни задачи, които имат за цел да развият алгоритмични умения и** програмни техники** 

Кавички да се оправят

**Comment by udarensamolet** [comment]
Fixed with [6aed922](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/6aed922b5d2497c69b28e4bb59e49753258736c7)
