### ISSUE TITLE
Грешка *

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#76]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions.md

Също така условието може да се замени като се направи променлива за крайната дата, т.е. 31 декември в крайната година и да се сравняват директно двете дати.*

Каква е тази звезда * на последния ред?

**Comment by udarensamolet** [comment]
Fixed with [2b2b260](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/2b2b260a0db22ca66320b061b2bf50f51870f9e3)
