### ISSUE TITLE
Позволена памет

### ISSUE THREAD

**Issue by kaykayehnn** [SoftUni/Programming-Basics-Book-CSharp-BG#78]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md
## Описание
Задача бикове и крави, в джъдж позволената памет е 16МБ.
## Текущ текст
Позволена памет: 4 MB.
## Текст след поправката
Позволена памет: **16** MB.

**Comment by udarensamolet** [comment]
Fixed with [b932295](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/b9322a5e5f41668dbe73a4035c1a7ecca9b2b644)
