### ISSUE TITLE
Грешен примерен вход, условието може да се опрости

### ISSUE THREAD

**Issue by kaykayehnn** [SoftUni/Programming-Basics-Book-CSharp-BG#79]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-9-problems-for-champions-part-2.md
## Описание
Задача X Expression:
Началната стойност на израза е 4 + 6 / 5 + ( 4 * 9 - 8) / 4 * 2, после на мястото на последната четворка се появява седмица. Приоритетът не действията също не се взима под внимание, но това може да е била идеята на автора.

Казано е, че резултатът от математическия израз ще е в диапазона [-100000.00...100000.00], а в насоките се използва decimal, _с цел избягване на всякакви проблем с точността_. По- уместно е да се използва double, защото изходът трябва да се принтира с точност два символа след десетичния знак. В краен случай резултатът ще се състои от 8 цифри, включително тези зад десетичния знак, което е достатъчно за 14те символа точност на double.

Логическата проверка (0 <= symbol - '0' && symbol - '0' <= 9) може да се опрости до (symbol >= '0' && symbol <= '9').

**Comment by udarensamolet** [comment]
Примера е коригиран.

Приоритетът на действията е обяснен подробно в условието на задачата ("Израза се решава както би бил решен от калкулатор и може да съдържа скоби. Всичко в скобите се пресмята първо.")

Авторското решение е да се използва тип `decimal`.

**Comment by kaykayehnn** [comment]
4 + 6 / 5 + (4 * 9 – 8 ) / 7 * 2=13.2 , а не 8.57
3 + (6 / 5) + (2 * 3 / 7)* 7 / 2 *(9 / 4 + 4 * 1)=22.95, а не 110.63
Първо се изпълняват действията в скобите, после умножение и деление, след това събиране и изваждане. Резултатите са от WolframAlpha, така би ги сметнал калкулатор.

**Comment by Teodor92** [comment]
За логическата проверка - наистина може да се опрости, но целта на по-дългия вариант е ясно да покаже че `char` променливат трябва да се обработи преди да е число.

**Comment by Teodor92** [comment]
Примера наистина е грешен и има нужда от поправка. Приоритета трябва да се взима под внимание.

**Comment by udarensamolet** [comment]
Условието на задачата е подвеждащо. Решеният израз показва точно какво трябва да прави програмата, съответно и даденият в примера резултат е коректен. 
Променихме текста от условието. Прочетете го пак, ако смятате, че все още не е обяснено добре или вече е ок, оставете коментар.

**Comment by kaykayehnn** [comment]
Вече е ясно какво се иска.
В джъдж пише лимит за време 0.100с, а в книгата 0.15.

**Comment by kaykayehnn** [comment]
Оправено е.
