### ISSUE TITLE
неяснота

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#80]
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-3-simple-conditions-exam-problems.md

За целта **нека** първо си припомним конструкцията на логическата проверка:

Какъв е смисъла на нека??

Конструкция на логическата проверка:

**Comment by udarensamolet** [comment]
'Нека' е частица в българския език, изразяваща необходимост и подбуда. Използвана е уместно.
