### ISSUE TITLE
Грешка правописна

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#82]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-3-simple-conditions-exam-problems.md
## Описание
Защо Обем е с главна буква а на следващите редове с малка буква?

## Текущ текст
От конзолата се четат четири реда:

Първият ред съдържа числото V – **Обем** на басейна в литри – цяло число в интервала [1 … 10000].
Вторият ред съдържа числото P1 – дебит на първата тръба за час – цяло число в интервала [1 … 5000].
Третият ред съдържа числото P2 – дебит на втората тръба за час – цяло число в интервала [1 … 5000].
Четвъртият ред съдържа числото H – часовете, в които работникът отсъства – число с плаваща запетая в интервала [1.0 … 24.00].

## Текст след поправката

Първият ред съдържа числото V – обем на басейна в литри – цяло число в интервала [1 … 10000].
Вторият ред съдържа числото P1 – дебит на първата тръба за час – цяло число в интервала [1 … 5000].
Третият ред съдържа числото P2 – дебит на втората тръба за час – цяло число в интервала [1 … 5000].
Четвъртият ред съдържа числото H – часовете, в които работникът отсъства – число с плаваща запетая в интервала [1.0 … 24.00].

**Comment by udarensamolet** [comment]
Fixed
