### ISSUE TITLE
Грешка правописна

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#85]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-3-simple-conditions-exam-problems.md
## Описание
  345 (365 – 20 = 245) грешка при въвеждане сигурно
## Текущ текст
 20 почивни дни -> работните дни са 345 (365 – 20 = 245)
## Текст след поправката
 345 (365 – 20 = 345)

**Comment by vncpetrov** [comment]
Грешката е поправена.
