### ISSUE TITLE
Нещо се е счупило при конвертирането

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#90]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
излишен текст
## Текущ текст
<script src="/assets/js/video.js"></script>

**Comment by Teodor92** [comment]
Същият проблем, като при #45
