### ISSUE TITLE
Грешка при писане на думата

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#93]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
отдели грешка при писане на думата
## Текущ текст
а една част ще използваме два отдели цикъла, като оставяме на читателя сам да намери зависимостта между n и променливите на циклите. За първия цикъл може да използваме следните насоки:
## Текст след поправката
а една част ще използваме два отделни цикъла, като оставяме на читателя сам да намери зависимостта между n и променливите на циклите. За първия цикъл може да използваме следните насоки:

**Comment by udarensamolet** [comment]
Fixed with [502949a](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/502949a66d363871c60bf17a4726aace16f9a932)
