### ISSUE TITLE
Грешка в променливите

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#97]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
На първия ред е roofHeight се казва на следващия ред е roofLenght
Не е ясно roofHeight или roofLenght??

## Текущ текст
Изчисляваме дължината на покрива. Тя е равна на половината от n. Резултата записваме в променливата roofHeight.
roofLenght снимка

**Comment by udarensamolet** [comment]
Fixed with [718f7fa](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/718f7fa6aac43c8c2d5855108e1dc782dde516c6)
