### ISSUE TITLE
Неясноти

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-CSharp-BG#99]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-6-drawing-at-the-console.md
## Описание
Защо ползваме умалителното тиренца??  а не тирета??
изрисуваме  - изрисуваме картина но не изрисуваме тирета това да не е калеграфия??
## Текущ текст
Изчисляваме броя тиренца, които трябва да изрисуваме. Броят ще е равен на n - stars. Записваме го в променлива padding.
## Текст след поправката
Изчисляваме броя тирета, които трябва да отпечатаме. Броят ще е равен на n - stars. Записваме го в променлива padding.

**Comment by udarensamolet** [comment]
Fixed with [820b529](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/820b529bcfaeee7c13566f148ff4ef76d0bfb0fc)
